### PR TITLE
Add Gender Icons to Performers

### LINKED ISSUE #434: [Feature] Add Gender to the performer grid view
Hi there

As Gender support has been added now, it would be good to have Gender added to the grid view on performer page

Cheers

### PR DESCRIPTION
**Pull request by kermieisinthehouse**
Closes #434

This adds gender icons to the performer grid and detail pages. Gender types are i18n'd now, the code is adapted from stash-box.

Performer grid:
Screenshot from 2021-12-28 23-39-28
Screenshot from 2021-12-28 23-39-46

Performer detail:
Screenshot from 2021-12-28 23-40-18

### CODE REVIEW

**Comment by WithoutPants** [comment]
The gender icon should not be shown if gender is not set.

**Comment by kermieisinthehouse** [comment]
StashDB shows the the same thing if it's unset, although I can blank it out with no issue

**Comment by WithoutPants** [comment]
> StashDB shows the the same thing if it's unset, although I can blank it out with no issue

I can't comment on the stash-box decision, but at least for personal use, I don't think the icon gives more or better information when gender is unset that wouldn't be conveyed by just omitting the icon, and in my opinion is cleaner.

**Comment by WithoutPants** [comment]
Also, please add a classname to the gender icon control so that it can be manipulated via css.

**Comment by kermieisinthehouse** [comment]
Fixed both :)

**Pull request merged**
