### PR TITLE
Add query options for tags, performers, studios #29

### LINKED ISSUE #29: "Add logical Criteria to tags" | "Add logical searchs"
When you use in Makers  "Add Criteria" and select Tags you can add several tags but not exists logical criteria:
It would be interesting "Add Logical Criteria".Example:
Show scene with "tag A" and " tag B"
Show scene with "tag A" or "tag B"
The same functionality for search it would be interesting too.

### PR DESCRIPTION
**Pull request by WithoutPants**
Adds includes/excludes options for studios, and includes/includes all/excludes options for tags and performers. Resolves #29 

Includes returns scenes that include any of the values entered. (ie includes `[A,B]` returns scenes such as `[A,B], [A], [A,C], [B,C]`)
Includes all returns scenes that include all of the values entered (ie includes all `[A,B]` returns only scenes with this subset: `[A,B], [A,B,C]`, not `[A], [B,C]` and so on.
Excludes returns scenes that do not have any of the values entered (ie excludes `[A, B]` returns scenes with `[], [C],...` and not `[A], [A,B], [B], [B,C]` and so on.

I hope this wording is clear and usable enough.

### CODE REVIEW

**Comment by bnkai** [comment]
i get this 
`GraphQL error: Internal system error. Error <ambiguous column name: scene_id>`
when trying includes,excludes or includes_all on **scene tags** or **performers**
Also on **tags** INCLUDES,EXCLUDES and INCLUDES ALL give the same results , consistent with your INCLUDES ALL description

**Comment by WithoutPants** [comment]
> i get this
> `GraphQL error: Internal system error. Error <ambiguous column name: scene_id>`
> when trying includes,excludes or includes_all on **scene tags** or **performers**
> Also on **tags** INCLUDES,EXCLUDES and INCLUDES ALL give the same results , consistent with your INCLUDES ALL description

Not sure what's going on here. I retested with my production data, and all of that behaviour works as expected.

**Comment by bnkai** [comment]
Sorry @WithoutPants i should say got to **Markers** first and then try the filters.
For  the scenes part they work fine , i thought because you referenced 29 you also meant for the markers. The errors are for the Markers tab

**Comment by WithoutPants** [comment]
Didn't even realise the original issue concern markers and not scenes. Latest push should resolve the issues.

**Comment by bnkai** [comment]
Tested ok

**Comment by Leopere** [comment]
Tested and ready

**Pull request merged**
