### PR TITLE
Basic password security #3

### PR DESCRIPTION
**Pull request by WithoutPants**
Addresses #3 

Uses basic authentication. Added fields to the configuration settings tab for username and password. If both values are non-empty, then authentication is performed. Stores the username and password hash in the config file.

Includes a change to SettingsConfigurationPanel.tsx to use `value` instead of `defaultValue` since the latter was causing the settings to become unsynced (I cleared a field and the internal model wouldn't update its value).

Note that due to #83 it's dangerous to change the settings in the configuration settings tab. I fixed this by removing the watch on the config file. I can add that change to this branch if required.

### CODE REVIEW

**Comment by Leopere** [comment]
Thanks for using bcrypt

**Comment by Leopere** [comment]
What does the auth protect specifically?  Is it for the configuration or the entire app?

**Comment by bnkai** [comment]
From what i understand it protects the app when it  starts? If we authenticate once it keeps running unprotected? I couldn't find any session cookies in the code ?

**Comment by WithoutPants** [comment]
It protects the entire app. Basic authentication works by setting the credentials once in the browser. While the browser is open, those credentials are kept. If the required credentials change, then the user must relogin with the new credentials. Otherwise, the user is kept logged in until they close the browser.

**Comment by bnkai** [comment]
Cool. I missed the call to basic auth....
I'll give it a try tonight.

**Comment by bnkai** [comment]
Just tried it and it works good like you said.

**Comment by WithoutPants** [comment]
Resolved conflicts. Ready to retest.

**Comment by bnkai** [comment]
I will test later allong with the other PRs

**Comment by bnkai** [comment]
Update
Retested!
Everything works fine ....

**Comment by WithoutPants** [comment]
I'm not sure where to document this:

Be aware that having user credentials prevents the node debugger version of the UI (on port 3000) from accessing the system due to CORS issues. Removing the username and password fixes the issue.

**Comment by Leopere** [comment]
I think that at the very least @WithoutPants documenting things in the README.md is helpful.

**Pull request merged**
