### PR TITLE
feat: UI - Performer scraper result list with image and basic data

### LINKED ISSUE #2695: [Feature] Performer scraper result list with image and more
**Is your feature request related to a problem? Please describe.**
Yes, Sometimes there are several results with aliases and more which I have to go through each one by one to see their Image.
If the images have been right there in the result list, then I was able to better and faster choose the correct one.

**Describe the solution you'd like**
The same scraper results view as scenes.

**Describe alternatives you've considered**
Nothing

### PR DESCRIPTION
**Pull request by TgSeed**
As the title says, but also added toast and error messages.

closes #2695

### CODE REVIEW

**Comment by TgSeed** [comment]
Stashbox functionality for this part (Performer scraper) might have got disabled/non-functional.
I have no idea how that works and don't have stash box access to test and try to make it functional.

Can anyone please contribute or help with this? Thanks.

**Comment by TgSeed** [comment]
There are also some minor contributions to #571 in this pull request.

**Comment by TgSeed** [comment]
post-scraping items in cache.ScrapeName is not done for scenes, and it might need to be done there too or neither.

It solves my issue where I use stash on my phone via my computer local network IP, but my phone has no internet access/cannot access the images' origin url while my computer can and is connected to the internet.
Post scraping converts the images' origin url to base64, so the image will be displayed on my phone too, even without internet access.

**Comment by TgSeed** [comment]
[80d138a](https://github.com/stashapp/stash/pull/2697/commits/80d138a5b2e403ab1d93a045b3f452fe59eef262) has resolved the merge conflicts that has been recently occurred.

**Comment by HijackHornet** [comment]
If this works, big up to you, this feature is much needed !

**Comment by WithoutPants** [comment]
Closing in favour of #3499, please see my comments there.

**Comment by TgSeed** [comment]
@StashPRs I am glad that you did it, hope that gets merged anyway.
Thanks

**Pull request closed without merging**
