### PR TITLE
Additional performer urls

### PR DESCRIPTION
**Pull request by 7dJx1qP**
Basic support for additional performer urls, partial solution to https://github.com/stashapp/stash/issues/1868. Adds a performers_urls table (performer_id, url). It doesn't replace the performer url field and I haven't made an attempt to integrate the additional urls with any other features like scraping or filtering. For now it's just a simple way to store additional performer urls.

Edit tab
image

Details tab
image

### CODE REVIEW

**Comment by 7dJx1qP** [comment]
Refactored the input based on the stash-box integration input but with a scrape button added in. This removes the need for an edit button, because the urls are edited in place.
image

**Comment by WithoutPants** [comment]
I couldn't find where this was documented, but the intent was to generalise our existing URL fields into a type/url table.

That is, where we currently have URL, Twitter, Instagram, we would instead have three URL entries in the table: one for website, one for twitter and one for instagram. The UI would be a pair of text fields. We could then use the entries to populate the top links bar by looking for hard-coded strings.

**Comment by reapier** [comment]
@7dJx1qP Any reason why this PR was closed? Mind if if open a similar PR to try to get this in?

**Comment by reapier** [comment]
@WithoutPants should this PR be update to match this change: https://github.com/stashapp/stash/pull/3852/commits

**Pull request closed without merging**
