### PR TITLE
Reload scrapers button

### PR DESCRIPTION
**Pull request by WithoutPants**
Adds an entry in the scrapers button to refresh loaded scrapers. This is for when scrapers are modified, added or removed. Changes to the scrapers will not come into effect until the scrapers are reloaded or the system is restarted.

### CODE REVIEW

**Comment by bnkai** [comment]
I'm having trouble rendering the scrape menu in the scene edit menu. 
It doesn't show anything except the save and delete button (the scrape button appears works/ok).
I think `QueryableScrapers` is empty for some reason.

**Comment by WithoutPants** [comment]
The scene scraper menu is populated by scrapers that have the `sceneByFragment` section. See #236 and #269 for examples.

Changed so that the scene scraper menu now always displays for the reload option even if there are no queryable scrapers.

**Comment by bnkai** [comment]
The xpath samples I think didn't have the sceneByFragment so it didn't make it in most ( if not all) of the xpath scene community scrapers. What should be the "action :" part for an xpath scraper? The scraper name?

**Comment by WithoutPants** [comment]
`sceneByFragment` doesn't currently support xpath scrapers.

**Comment by WithoutPants** [comment]
The action field will need to be `script` or `stash`.

**Comment by bnkai** [comment]
Works ok for me. Both scene and performer section.

**Pull request merged**
