### PR TITLE
Add LICENSE until we get all signers on the switch

### PR DESCRIPTION
**Pull request by Leopere**
For now, all subsequent commits should be against the appropriate license.

Related pre-requisites for switching from a SUBLICENSE file to just LICENSING this code to AGPL fully.
#276 #277

### CODE REVIEW

**Comment by bnkai** [comment]
I think it is better to add this ASAP . Is there antyhing else needed to change to make every commit from now on with this license or to select this license when you make a PR ?

**Comment by WithoutPants** [comment]
Why the urgency for this? Unless we get an influx of PRs from new contributors (which we don't have to approve until we change the license), I don't see why we can't wait for the sign off and change the license entirely.

**Comment by FleetingOrchard** [comment]
Not to be a jerk, but WP is on the money here. The license is only ever going to be relevant if IP drama goes down -- as in, at that specific moment in time, and not sooner.

In the meantime, if we want to continue to bring in new contributors (assuming somehow the switch ends up taking longer than expected), maintainers can just make getting an RP in conditional on that contributor "signing off" on AGPL.

Ultimately I'd suggest not worrying too much about this. There's enough being done here already that's not technically by the book but will probably fly on count of commonly understood meaning and intent, having things be a bit in limbo for a while is going to be fine.

**Comment by Leopere** [comment]
No real urgency so much as an option because we have a number of people contributing if new contributors contribute and we're planning on the switch we would thus need them to agree to the license change along with their PR before we could accept it however with a SUBLICENSE it might be less stress involved.

As I am still somewhat iffy on this myself I put it up for review from the other major contributors to Stash.

**Pull request merged**
