### PR TITLE
Port Movies UI to v2.5

### PR DESCRIPTION
**Pull request by WithoutPants**
Ported the Movies UI to the 2.5 UI.

### CODE REVIEW

**Comment by bnkai** [comment]
I'm getting a something is wrong error as soon as i click a movie e.g. `http://localhost:9998/movies/1`
the full error from the inspector 
```
TypeError: "ye is undefined"
    el Movie.tsx:105
    React 7
        la
        Wa
        Ec
        vs
        ps
        os
        Gi
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        qi
        Gi
        Wi
        es
        ka
    next QueryData.ts:282
    g Observable.js:135
    O Observable.js:179
    value Observable.js:235
    g ObservableQuery.ts:701
    g ObservableQuery.ts:701
    next ObservableQuery.ts:662
    i QueryManager.ts:518
    queryListenerForObserver QueryManager.ts:644
    broadcastQueries QueryManager.ts:1091
    broadcastQueries QueryManager.ts:1087
    broadcastQueries QueryManager.ts:1085
    g QueryManager.ts:1237
    next Observable.js:322
    g Observable.js:135
    O Observable.js:179
    value Observable.js:235
    next observables.ts:12
    next observables.ts:12
    g Observable.js:135
    O Observable.js:179
    value Observable.js:235
    f httpLink.ts:142
react-dom.production.min.js:196:194
    React 5
        fc
        callback
        Oo
        go
        gs
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
        qi
        bs
        os
        Gi
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        qi
        Gi
        Wi
        es
        ka
    next QueryData.ts:282
    g Observable.js:135
    O Observable.js:179
    value Observable.js:235
    g ObservableQuery.ts:701
    g ObservableQuery.ts:701
    next ObservableQuery.ts:662
    i QueryManager.ts:518
    queryListenerForObserver QueryManager.ts:644
    broadcastQueries QueryManager.ts:1091
    broadcastQueries QueryManager.ts:1087
    broadcastQueries QueryManager.ts:1085
    g QueryManager.ts:1237
    next Observable.js:322
    g Observable.js:135
    O Observable.js:179
    value Observable.js:235
    next observables.ts:12
    next observables.ts:12
    g Observable.js:135
    O Observable.js:179
    value Observable.js:235
    f httpLink.ts:142​

```

**Comment by WithoutPants** [comment]
Dumb mistake trying to fix a linting issue. Fixed.

**Comment by bnkai** [comment]
a small glitch when you add a new movie and type in the name field
doublename
the movie name is shown doubled to the left above the "Name" part

**Comment by bnkai** [comment]
lol it was the placeholders for the covers nvm

**Comment by bnkai** [comment]
The `Movies/Scenes` , `Scene Index` functionality is missing from the `Scene -> Edit ` panel  ( scenes cannot be added to movies )

**Comment by WithoutPants** [comment]
Added the missing scene/movie relationship functionality.

**Comment by bnkai** [comment]
Everything works ok for me.
The only glitch is the movies synopsis for me as it is still too small imo.

Can we take it out of the table so that it takes the whole area (doubling the width) ?
The title part of it takes space that can be better used for the synopsis and maybe even the url.
Switching to title above data (instead of left) also makes for room for the synopsis / url.

**Comment by WithoutPants** [comment]
Moved URL and synopsis to their own rows.

**Pull request merged**
