### PR TITLE
Fix database locked errors

### LINKED ISSUE #3053: [Bug Report] Cannot perform any 'Update' operations while a long running process (AutoTag or Scan (with new scenes added) is running
**Describe the bug**
When (1) long running task occurs, then a second  'update' task occurs while the long running task is still running.  An error appears:

> updating scenes: executing `UPDATE `scenes` SET `date`=?,`details`=?,`rating`=?,`studio_id`=?,`title`=?,`updated_at`=?,`url`=? 
> WHERE (`scenes`.`id` = ?)` [[0001-01-01 <nil> <nil> SceneName 2022-10-25T14:56:06-04:00 > > https://someUrl.com/movies/someMovieTitle-cj 3082]]: database is locked

Another example of error:
> error executing `UPDATE studios SET checksum=:checksum, name=:name, url=:url, updated_at=:updated_at, rating=:rating, details=:details, ignore_auto_tag=:ignore_auto_tag WHERE studios.id = :id` [[{1524 0xc03c342240 0xc03b5e8630 0xc03b5e8648 <nil> <nil> 0xc03b5e8618 0xc09e2a3350 0xc03b5e8660 0xc09e2a3320}]]: database is locked

**To Reproduce**

1. Go and run a long running task (either scan with **new** files, or **auto update**
2. Update some existing data, such as a scene, or studio, or performer
3. Upon clicking 'save' on the update of data, the error will appear

**Expected behavior**
Update (scene / performer / studio ) is successful while a long running background task is running

**Screenshots**
Error messages above

**Stash Version: v0.17.1:**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chromium-> Thorium 
 - Version 107.0.5256.0 (Official Build) (64-bit)

 

**Additional context**
* My threads are set to '0' (auto)
* Core i7-10700K @ 5GHZ
* Not running in Docker (Installed on 'bare-metal')

### PR DESCRIPTION
**Pull request by WithoutPants**
Fixes #3053 

Once again re-introduces exclusive write transactions. Concurrent threads writing to the database cause `database is locked` errors. `txn.WithTxn` now starts a transaction in `exclusive` mode. This uses a channel to ensure only one goroutine has an exclusive transaction at any given time. Adds `txn.WithReadTxn` which starts a transaction without this `exclusive` mode, meaning that any number of threads can start transactions with this method. It is assumed but not enforced that the calling code _will not_ modify the database. Doing so within a read transaction may cause `database is locked` errors.

Converted most read-only resolvers etc to use `txn.WithReadTxn`.

In my testing, I'm not seeing any significant performance impact.

### CODE REVIEW

**Comment by bnkai** [comment]
From a quick test it seems that there are some issues

Tested scanning (only generate phashes ticked ) with parallel tasks set to 5, issues are present when trying again with 1 
- while scanning there is an issue with the graphql api. It seems to block  and so no scene on post create plugins can utilize the api and no save via  scraping (tagger or scrape via the scene edit) works while the scanning is ongoing
More specifically for plugins the `titleFromFilename` plugin errors out due to 
```
Scene.Create.Post [titleFromFilename]: returned error: [FATAL] Exception with GraphQL request. HTTPConnectionPool(host='localhost', port=9998): Read timed out. (read timeout=20)
```
Other plugins utilizing the database directly ( via python sqlite) seem to work


- cancelling the scan task sometimes works ok

```
ERRO[2022-11-18 21:26:42] error executing post hooks: operation cancelled 
ERRO[2022-11-18 21:26:42] context canceled                             
INFO[2022-11-18 21:26:42] [generator] generating phash sprite for /home/user/xxxx.mp4 
ERRO[2022-11-18 21:26:42] context canceled                             
INFO[2022-11-18 21:26:42] Creating screenshot for /home/user/xxx2.mp4 
ERRO[2022-11-18 21:26:42] Error generating cover for /home/user/xxx2.mp4: error starting command: context canceled 
ERRO[2022-11-18 21:26:55] context canceled 
ERRO[2022-11-18 21:26:55] context canceled                             
ERRO[2022-11-18 21:27:08] context canceled                             
ERRO[2022-11-18 21:27:13] context canceled                             
INFO[2022-11-18 21:27:13] Stopping due to user request 
```
and sometimes panics out
```
ERRO[2022-11-18 21:14:20] context canceled
ERRO[2022-11-18 21:14:20] error executing post hooks: operation cancelled
INFO[2022-11-18 21:14:20] Creating screenshot for /home/user/xxx3.mp4
ERRO[2022-11-18 21:14:20] Error generating cover for /home/user/xxx3.mp4: error starting command: context canceled
panic: send on closed channel

goroutine 6172 [running]:
github.com/stashapp/stash/pkg/job.(*TaskQueue).Add(...)
        github.com/stashapp/stash/pkg/job/task.go:35
github.com/stashapp/stash/internal/manager.(*sceneGenerators).Generate(0xc0007c4080?, {0x16ffb7f?, 0x21?}, 0xc0026e3d40?, 0xc000341490?)
        github.com/stashapp/stash/internal/manager/task_scan.go:409 +0x367
github.com/stashapp/stash/pkg/scene.(*ScanHandler).Handle.func1({0x1c59a00, 0xc00079a300})
        github.com/stashapp/stash/pkg/scene/scan.go:131 +0x1ea
github.com/stashapp/stash/pkg/txn.executeHooks(...)
        github.com/stashapp/stash/pkg/txn/hooks.go:34
github.com/stashapp/stash/pkg/txn.executePostCommitHooks({0x1c59a00, 0xc00079a300})
        github.com/stashapp/stash/pkg/txn/hooks.go:40 +0x74
github.com/stashapp/stash/pkg/txn.commit({0x1c59a00, 0xc00079a300}, {0x1c5b340?, 0xc0007c41c0?})
        github.com/stashapp/stash/pkg/txn/transaction.go:108 +0x55
github.com/stashapp/stash/pkg/txn.withTxn.func1()
        github.com/stashapp/stash/pkg/txn/transaction.go:80 +0xe5
github.com/stashapp/stash/pkg/txn.withTxn({0x1c59a00?, 0xc000a25920?}, {0x1c5b340?, 0xc0007c41c0}, 0xc0007d1c10, 0x30?, 0x0)
        github.com/stashapp/stash/pkg/txn/transaction.go:87 +0x1b8
github.com/stashapp/stash/pkg/txn.Retryer.WithTxn({{0x1c5b340?, 0xc0007c41c0?}, 0xc000a25920?, 0x0?}, {0x1c59a00, 0xc000a25920}, 0x1?)
        github.com/stashapp/stash/pkg/txn/transaction.go:151 +0xe6
github.com/stashapp/stash/pkg/file.(*scanJob).withTxn(...)
        github.com/stashapp/stash/pkg/file/scan.go:138
github.com/stashapp/stash/pkg/file.(*scanJob).onNewFile(0xc0007d6000, {0x1c59a00, 0xc000a25920}, {0xc002659130, {0x1c5ae40, 0x27c7fb8}, {0x1c5c410, 0xc002655a00}})
        github.com/stashapp/stash/pkg/file/scan.go:637 +0x539
github.com/stashapp/stash/pkg/file.(*scanJob).handleFile.func1({0x1c59a00, 0xc000a25920})
        github.com/stashapp/stash/pkg/file/scan.go:546 +0x165
github.com/stashapp/stash/pkg/txn.WithDatabase({0x1c59958?, 0xc000362000?}, {0x1c52360?, 0xc002d37480?}, 0xc00065cda8)
        github.com/stashapp/stash/pkg/txn/transaction.go:130 +0x5f
github.com/stashapp/stash/pkg/file.(*scanJob).withDB(...)
        github.com/stashapp/stash/pkg/file/scan.go:142
github.com/stashapp/stash/pkg/file.(*scanJob).handleFile(0xc0007d6000, {0x1c59958, 0xc000362000}, {0xc002659130, {0x1c5ae40, 0x27c7fb8}, {0x1c5c410, 0xc002655a00}})
        github.com/stashapp/stash/pkg/file/scan.go:537 +0x1c5
github.com/stashapp/stash/pkg/file.(*scanJob).processQueueItem.func1()
        github.com/stashapp/stash/pkg/file/scan.go:381 +0xa6
github.com/stashapp/stash/pkg/job.(*Progress).ExecuteTask(0xc000993ea0, {0xc002ff8d20, 0x5b}, 0xc00306c730)
        github.com/stashapp/stash/pkg/job/progress.go:175 +0xcd
github.com/stashapp/stash/pkg/file.(*scanJob).processQueueItem(0xc0007d6000, {0x1c59958?, 0xc000362000}, {0xc002659130, {0x1c5ae40, 0x27c7fb8}, {0x1c5c410, 0xc002655a00}})
        github.com/stashapp/stash/pkg/file/scan.go:376 +0x152
github.com/stashapp/stash/pkg/file.(*scanJob).processQueue.func1()
        github.com/stashapp/stash/pkg/file/scan.go:341 +0x78
created by github.com/stashapp/stash/pkg/file.(*scanJob).processQueue
        github.com/stashapp/stash/pkg/file/scan.go:339 +0x107
```

**Comment by WithoutPants** [comment]
Thanks for testing. The phash generation code was incorrectly hanging onto the transaction, causing other threads to take longer to access a write transaction. Should now be fixed.

The panic was due to cancelling the task while it was still queuing files. This should now be fixed as well.

I've also suppressed some of the context errors that occur due to cancelling tasks. I expect we will see more, which I can suppress as well, but I don't consider them showstoppers.

**Comment by Teda1** [comment]
I tested this change by running both a single-threaded and a multithreaded scan with all the generate options turned on against one of my studio directories containing many scenes and galleries. Whiles the tasks were running; I did not run into issues tagging scenes or modifying existing data. Things seem to be in much better shape.

**Comment by bnkai** [comment]
> I tested this change by running both a single-threaded and a multithreaded scan with all the generate options turned on against one of my studio directories containing many scenes and galleries. Whiles the tasks were running; I did not run into issues tagging scenes or modifying existing data. Things seem to be in much better shape.

Can confirm the above as well. The cancelling task issue is also resolved.

**Review by bnkai — APPROVED** [review]

**Pull request merged**
