### PR TITLE
[WIP] add v3 vue ui

### PR DESCRIPTION
**Pull request by endqwerty**
vue ui
Using vue-cli generated with the following settings: Typescript, class components, eslint recommended, prettier, sass, vuex, vue router, no HTML5 history, jest, nightwatch

of note, no HTML5 history since that will require server config for handling index fallback (https://router.vuejs.org/guide/essentials/history-mode.html)

### CODE REVIEW

**Comment by Leopere** [comment]
I would love to see some screenshots of the proposed changes to the UI in here for reference and discussion.

**Comment by Leopere** [comment]
This will also need to undergo loads of testing to ensure that we don't see huge UI regressions in the transition.

**Comment by WithoutPants** [comment]
Is there a central issue for this change to discuss the UI rewrite?

**Comment by endqwerty** [comment]
No idea. There's the discord channel which I was added to.

**Comment by endqwerty** [comment]
e2e and unit test frameworks are added. Additional focus and comments on there will be helpful as this progresses.

Just checking, not sure where the discord convo ended up, we're good on using Vuetify right?

**Comment by endqwerty** [comment]
For reference, this is the UI now. I'll update and post screenshots as I update it. Annotation 2019-11-17 214453

**Comment by endqwerty** [comment]
closing this since its vuetify (material design) and not what we're looking for. Someone will reopen a PR once we have a solid understanding of what we're using/making.

**Pull request closed without merging**
