### PR TITLE
Default create missing to true in Identify

### PR DESCRIPTION
**Pull request by WithoutPants**
Defaults create missing studios/performers/tags to true in the UI.

Supercedes #4857

### CODE REVIEW

**Comment by DogmaDragon** [comment]
I would suggest adding a warning or suggesting making a backup somewhere on the identify interface modal, since the task is irreversible.

**Comment by WithoutPants** [comment]
> I would suggest adding a warning or suggesting making a backup somewhere on the identify interface modal, since the task is irreversible.

Is this a blocker to merging this change? I don't have a simple solution for adding such a warning currently, so I'll defer this change to the next release if we think it's destructive without accompanying warnings/documentation.

**Comment by Ronnie711** [comment]
I've been deep diving with Identify over the past few days & have nearly finished with it. As I said on Discord @DogmaDragon I'm going to write up a sort of 'How to' and explain all the options. I do agree it could do with a disclaimer but I wouldn't call it a blocker at this stage as this change seems to be adding basic functionality which doesn't break how it's currently working.

I had Identify running with the current defaults and it half identified because I'd forgotten to set these changes from the current default (which seems to be a common complaint on discord).

I'll try and put down some thoughts on what could be potentially improved over the next few days and open an issue for everyone to expand on :)

**Comment by DogmaDragon** [comment]
> Is this a blocker to merging this change? I don't have a simple solution for adding such a warning currently, so I'll defer this change to the next release if we think it's destructive without accompanying warnings/documentation.

I wouldn't say it's a blocker. Some people tend to run the task not fully understanding what it does and then come to ask if they can reverse it somehow. It would just be a big quality of life for both users and support people.

**Pull request merged**
