### PR TITLE
Update apple touch icon

### PR DESCRIPTION
**Pull request by Teda1**
I assume the `ui/v2.5` directory is the correct place to put this icon. Let me know if it needs to be moved.

### CODE REVIEW

**Comment by kermieisinthehouse** [comment]
Can you post screenshots of what this looks like in context, before and after?

Also, note that static assets are now generated from a master icon using https://github.com/stashapp/stash/blob/develop/scripts/generate_icons.sh

**Comment by Teda1** [comment]
I, unfortunately, haven't set up a proper local dev environment yet which is why I've been tackling more minor items like this. Hopefully, by the end of this week, my environment will be set up. Until then all I can provide for now is a reference to metart.com and how they currently handle this
Screenshot 2022-02-07 184225
unnamed

**Comment by Teda1** [comment]
I just got around to setting up my environment. here are the screenshots:
IMG-1250
IMG-1251

**Comment by Teda1** [comment]
It does. The background with the favicon.png is just pitch black. I'll revert my change and get a screenshot. Give me a sec

**Comment by Teda1** [comment]
IMG-1250 (1)

IMG-1251 (1)

The favcon.png isn't bad. I just don't think it's a proper icon.

**Comment by kermieisinthehouse** [comment]
Hmm, I can't find any way to set the background color dynamically. Having a dedicated one seems to be the way to go. Can you rename it apple-touch-icon.png to meet the standard?

**Comment by Teda1** [comment]
Hey Kermie, just wanted to make sure you weren't waiting on me for anything else regarding this pr

**Pull request merged**
