### PR TITLE
(Automated!) Translation updates

### PR DESCRIPTION
**Pull request by kermieisinthehouse**
This is mostly a test of https://translate.stashapp.cc . I see it treats whitespace a little differently so the diff is useless.

This brings Italian up to parity with en-GB, and a significant amount of Spanish fixes.

Huge thanks to failead0r and BViking76 for the translations themselves.

### CODE REVIEW

**Comment by peolic** [comment]
can you set indent to 2 spaces?
https://docs.weblate.org/en/latest/admin/addons.html#customize-json-output

**Comment by kermieisinthehouse** [comment]
Thanks for the heads up, but I'm not sure if I can apply this retroactively without losing changes. 

Next translation batch will feature them.

**Comment by peolic** [comment]
In any case, you can view changes while ignoring whitespace - https://github.com/stashapp/stash/pull/2018/files?w=1

**Comment by kermieisinthehouse** [comment]
Shoutout to philipw99 for the zh-CN help!

**Comment by kermieisinthehouse** [comment]
Shout-out to Peter M. for helping bring German up to date! What an amazing start to this endeavor!!

**Comment by kermieisinthehouse** [comment]
Fixed merge conflicts

Please note this is blocking future translations

**Pull request merged**
