### PR TITLE
Add performer pairings/appears with tab to performers

### PR DESCRIPTION
**Pull request by dogwithakeyboard**
Adds a new "Appears With" tab to performers showing performers who are credited with the current performer in a Scene, Gallery or Image.

Clicking the popovers will show the Scenes/Movies/Galleries/Images filtered by the two performers.

This is my first time working with react and go so this is mostly based on the work done for studio performers. All misunderstandings and errors are my own!

### CODE REVIEW

**Comment by DogmaDragon** [comment]
Closes https://github.com/stashapp/stash/issues/1455

**Comment by kermieisinthehouse** [comment]
Thank you for your contribution! This is a useful feature.

Code reviewed and tested.

**Comment by WithoutPants** [comment]
@dogwithakeyboard you are eligible for the $25 bounty on the original issue. Please submit an expense to the OpenCollective, or nominate an alternative issue to assign the bounty to. Thanks for your contribution.

**Comment by dogwithakeyboard** [comment]
@WithoutPants I've had the satisfaction of contributing to a piece of software I use every day. Would it be possible to donate the bounty to the collective kitty?

**Comment by WithoutPants** [comment]
> @WithoutPants I've had the satisfaction of contributing to a piece of software I use every day. Would it be possible to donate the bounty to the collective kitty?

This is fine. I'll assign to the project. Thanks!

**Pull request merged**
