### PR TITLE
Recording Play/O Dates with Play Counter & History Panel

### PR DESCRIPTION
**Pull request by randemgame**
This pull request implements functionality that has been requested here https://github.com/stashapp/stash/issues/3392 and https://github.com/stashapp/stash/issues/3607 and https://github.com/stashapp/stash/issues/3680. I have been unable to commit fully to Stash due to this missing feature and wanting to transfer data I've recorded in older organisers. I feel this feature will be beneficial to all users wanting to keep a more accurate historical record of their Stash usage and is something that would ideally be implemented soon so that user's play/o date history can stop being lost to time.

Screenshot 2023-07-17 221856

The Play Counter is modeled on the O Counter and functions similarly. The icon is custom made myself for Stash and I think it fits nicely in the interface, but it's fine to replace it.

Incrementing/Decrementing or Resetting the Play Counter or the O Counter now writes or erases a date to two new tables in the SQL database called scenes_playdates and scenes_odates - consisting of an id, scene_id and play/odate. I have kept the odates and playdates in separate tables as per this comment from WithoutPants https://github.com/stashapp/stash/issues/3607#issuecomment-1487947899

The History Panel provides a view that consolidates date information currently spread across several panels, and further incorporates the new Play/O Date data to provide a chronological view; from when the scene was released to when the scene file was created to when it was added to Stash, updated in Stash and finally watched or O'd. While I have kept the Release Date in the main 'Details' window, I think the Created At/Updated At information is probably less relevant to be displayed there, compared to the scene's Director, Description, etc (i.e the difference between the scene's studio data and what is just specific to the file in stash). Likewise, I think the Play Count/Play Duration is out of place in the 'File Info' tab, whilst moving the 'File Modification Time' (i.e File Creation Time) along with all the other dates to the History Panel enables this interesting timeline, as visible in the attached screenshot. Each recorded Play or O Date then adds a new line to this display, but they can always be viewed at a glance and modified via the counters across all panels. There are a number of different implementations that presenting the Play/O Dates could have taken but I think I found a nice solution here in collating all the date data associated with a scene and presenting it in this linear timeline. 

Unfortunately, there is no way to record accurate dates from the existing play/o counter int data, other than the most recent played_at record (hence that urgency in having this functionality implemented sooner rather than later). Looking at the History panel as it reads chronologically from top to bottom, the 'Play Date Recorded' can at least be understood as sitting between the 'Created At' date and the most recent 'Play Date Recorded'. In the migration file I assigned the unknown play/o dates with the 'Created At' date as it is the most accurate estimate from the data. When viewed in this panel the user could observe that if the Created At and Play Date recorded were identical, it would be indicative of an estimated date recorded from before more accurate date data was being recorded. The most recent Played At date is being recorded in the SQL migration file at least.

The code in SceneHistoryPanel to display the play/o dates is really a temporary solution (it gets info from the counters and last_played_date of the scenes table, not the new dates in the new tables) so would ideally be updated once those dates are accessible from GraphQL queries. Unfortunately, after several weeks trying I just can not understand how to implement GraphQL correctly in the code-base to implement this myself.

I would have ideally included some functionality to edit the play/o dates displayed in the History Panel, but this is perhaps not so essential just yet. It is currently possible to add different dates by changing the system clock or editing the SQL database directly, which is the current working solution for pornganizer and porn-vault. Migration from these other programs is at least now possible, by writing the imported play/o date data directly to the SQL database. 

I have not in this pull included code to add the o dates to images. I felt that as Images do not have a production date or play dates that it is not as useful to have a History panel there. I was not sure of the ideal solution to detect if the Increment/Decrement/ResetOCounter in SQLite/common.go was being called by an image or video, so duplicated these funcs, moving the dupes to scene.go where they additionally update the ODates table. I renamed these funcs 'IncrementOCounterDate' etc to be more accurate (and maybe IncrementWatchCount etc should then also be renamed IncrementWatchCountDate accordingly?). Of course, this leaves the funcs in common.go only applying to Images which does not make them so 'common' anymore. I am sure there is a more elegant solution, but I had trouble myself trying to move the Add/Remove/Reset dates out of that func, adding to the SceneReaderWriter, getting lost and confused...

This is my first time working with Go, React, Type Script, GraphQL, etc and I found the code-base very complex to follow but have put in a lot of time to try and add this feature. I have had to give up on trying to implement the functionality to read data from the new tables as more and more files needed to be modified that I did not understand, and I was uncomfortable with the amount of changes that kept piling up. I hope you do not take too much offense at my beginner code and that there could still be a path to implementing it. I can really only follow simple instructions about any of the related code, so would be happy if anyone wanted to edit this to better fit the existing code, as I am aware that the existing code is structured in a very advanced manner.

There are a couple of issues that I am still struggling with. The most recent Play Date recorded does not display the correct time in the SceneHistoryPanel until the page is refreshed. I could not quite work this out. Also, the two new funcs in scene_test.go for ResetWatchCount and DecrementWatchCount are not actually testing anything, I could not guess what the correct code to fit here would be. Otherwise, it seemed to past all the validation checks. Thanks for your time!

### CODE REVIEW

**Comment by jpnsfw** [comment]
Thanks so much for working on this! I just tried it and had a few notes:

- Play count should probably not have Decrement and Reset buttons.
- History tab just shows "O Date Recorded" with no text, even for new O's. Looks ok in the DB though.

**Comment by HijackHornet** [comment]
> * Play count should probably not have Decrement and Reset buttons.

I think it's good to have. I would use it. Specially when editing metadata and playing by mistake

**Comment by randemgame** [comment]
Hey, re History tab just shows "O Date Recorded" - it is just using the data from the scenes table to populate this view atm, not the data from the two new tables. I spent a lot of time trying to create the graphql code to read from these new tables but I could never get it working right and it required writing to so many different files that I didn't understand that it got very overwhelming each time. I thought best to do a pull request with the functionality I already added and then I could either try and add that code afterwards or perhaps someone who could implement it with less trouble could take the lead. Also, I think decreasing and resetting plays is worth including for a few different use cases that could pop up.

**Comment by randemgame** [comment]
Nice to see this on the milestone and I'll work to improve it but I will be away for the next couple of weeks

**Comment by echo6ix** [comment]
Love the idea of a history tab that focuses on playback stats per the feature requests you're referencing. But I think the History tab loses focus when incorporating other fields just because they have a date. The amalgamation of some of these fields is a bit counterintuitive imo.

**File modification time** field --> *File Info* tab --> Because it's data about the file
A _file modification time_ field in the _file info_ tab is already a very intuitive placement, as the tab's name directly indicates its relevance to the file. It's also a seamless presentation when dealing with scenes that have multiple files. Moving this field to another tab would be a regression imo.

**Release date** field --> *[Scene] details* tab --> Because it's studio metadata about the scene (independent of Stash)
I don't see the relevance of this field in a primarily playback stats container.

**Created at** and **Updated at** fields --> *[Scene] details* tab --> Because it's Stash metadata about scene
Same comment as above.

(As an aside, the current placement of these two fields is logical, but ideally they should be partitioned with their own sub-heading that indicates they are Stash metadata about the scene, distinct from studio metadata about the scene)

This is how I personally view the logical structure of the scene's metadata

```
Scene:
  Details:
    Scene metadata:
      - Code
      - Details (description)
      - Director
      - Performers
      - Release date
      - Tags
      - Title
      - URLs
    Stash metadata:
      - Date/Created at
      - Date/Updated at
      - Rating
      - StashID
      - Stream URL
  File(s):
    General:
      - File/Modification time
      - File/Size
      - File/Pathname
    Video:
      - Bit rate
      - Codec/audio
      - Codec/video
      - Dimensions
      - Duration
      - Frame rate
      - Resolution
    Hashes:
      - Hash
      - Checksum
      - PHash
  Playback history:
    - O-counter count
    - Play count
    - Play duration
    - Etc
```

**Comment by randemgame** [comment]
Sorry, I was away for holidays then super busy with work this last month. 

As a video collector, I really liked seeing all the dates together and sorted chronologically - it's a nice overview of the scenes journey from the production to my collection to my latest activity. I think it adds more utility and purpose to the History panel which is not going to be entirely filled with playback data in most cases, rather than detracting from any focus. However, I suppose this is down to personal preference! I reverted the moved fields in respect of @echo6ix request -> https://github.com/stashapp/stash/pull/3922/commits/a3742144510e3bf5211ad65d74a54ff31fa2c91a

If I can understand how to add to the settings, perhaps the additional history data could be added as a toggle via an 'Expanded History / Timeline' option. Alternatively, if such functionality could be added with a plugin then that would be enough for me. I don't know if that's possible either via Tampermonkey or a JS plugin?

Anyway, the priority with this pull request has been to start recording the play dates and o dates more accurately, so I will isolate that for now. The only fields that have moved or altered now are the play count/play duration.

I am still struggling to make any progress implementing the GraphQL functionality necessary to read data from the new o/playdates tables to display in the History Panel and would appreciate help with that.

**Comment by forsexonly93** [comment]
@randemgame @WithoutPants Hey guys, any updates on this actually it's a great feature and would be really helpful to get this out sooner than later to avoid losing the records IMO.

**Comment by randemgame** [comment]
Thanks @forsexonly93 for the message. I will attempt to fix up the conflicts again over the holidays, but I have been waiting on some feedback or comments on this from the leadership for several months now. To be honest, I had been hoping from the start that someone more experienced could help me implement this, as happened with the original track activity push here https://github.com/stashapp/stash/pull/3055. I have a hard time understanding the code base or languages involved, which has made it difficult and time consuming whenever I have tried returning to this code to address the regular update of conflicts that pop up. I am still doubtful that I wrote any of this code appropriately, which makes me lack confidence in adding more bad code on top of the existing bad code I presented here.

I was a little bummed out to remove the collated and chronological date information I had designed the whole History panel concept around, as per @echo6ix's request. However, as that was the only feedback I received here, I did respond to it in a timely fashion with my last update and made the requested changes. Since there hasn't been much interest in the original concept since, this feature seems to be unpopular or else I did not communicate the value of it well enough to users. I have lost some enthusiasm for this pull request since stripping the History panel of it's original unique selling point, and the lack of feedback here hasn't helped. Regardless, I still would like to record play dates and odates properly, as the lack of this feature continues to prevent me actually using Stash! 

I am doubtful that displaying the playdates/odates alone are really enough to warrant this additional 'History' tab anymore, so would it probably be more economical to just add these dates to the bottom of the 'File Info' panel? It's elegant enough to show the play/o counter as a number next to the related button, so the Playback History as proposed by @echo6ix above would really only be showing the odates/playdates as unique information. For unwatched scenes this would just be a blank tab and I think that's a waste of UI real estate. My opinion is that if the original concept of the History Panel is not wanted, then the play/o dates should be displayed somewhere else in the interface, probably in 'File Info'. 

While I respect the opinion of @echo6ix and made these adjustments to suit them, it would have been nice to get feedback from any other users who might have appreciated the original proposal of the History Panel as a chronological timeline of the scene's journey from production date to arrival on the hard drive to watched and o'd by the user. I did ask in my last comment whether we could have this feature as an optional setting, but I didn't get a response on that. I am not sure how to better argue my proposal here.

I am also not sure how these dates should be displayed, I have only been able to implement them as plain text. Should they be editable? (there are use cases I mentioned in my first post for editable dates, but then nothing else is editable in the File Info panel) I also thought the dates should update automatically with the play and o button being pressed, but I had some difficulty resolving this. Would it be necessary with this push to include adjustments to other code so that this new date information would be utilized e.g. when ordering the scenes by date? I was hoping to implement some of this feature before getting to this more advanced integration but I wonder if these are the concerns that have prevented the pull request being advanced further yet.

I'm a bit disheartened to see that this commit has been removed from any milestone without comment or ceremony, which makes me less enthusiastic to spend more time on this (the original commit took a month of my time and I have much less time available now). I have checked this page regularly and have been available on Discord, to respond to any discussion. Could @WithoutPants please advise on a way forward with this request? I would be willing to contribute a bounty if you or someone else could help me implement this feature. It would probably make more sense for me financially to pay for help rather than lose more of my time to working on this, but I am still committed to working on this pull request as long as it takes and spending that time if necessary - I just need some guidance that such time would not be spent in vain. Apologies for the wall of text again, and of course I wouldn't expect any response until after the holidays.

**Comment by randemgame** [comment]
Hey @WithoutPants, I would be happy for you to take it from here, that would be great. It's tough for me to return to this as I don't use these languages elsewhere so I have to relearn basic stuff every time and as I mentioned above, I expect there needs to be some work fitting this all in the code better. I hope something in here was useful but I'd totally understand if you need to throw it all out. The way I built it would have enabled me to run a custom python script on the stash DB to add play/o history to scenes from another DB, that was my main objective so hopefully something like that will be possible. Many Thanks!

**Comment by WithoutPants** [comment]
Closing in favour of #4532.

**Pull request closed without merging**
