### PR TITLE
Add test and integration tests to the Makefile

### PR DESCRIPTION
**Pull request by WithoutPants**
Currently, travis runs `go test` which only tests the top-level package. Added `test` and `it` targets to the Makefile. `test` performs unit tests on the entire package tree. `it` performs integration tests (denoted in the test files with `// +build integration`).

I've changed the travis file to run `make test` on all builds, and `make it` on master builds, though this could possibly be changed to include the develop branch as well.

The change to `generator.go` was the result of running `make test` finding an error. This was latent due to travis running `go test` only.

Finally, I've added a `gitattributes` file to prevent the `go.mod` and `go.sum` files from showing as modified on Windows after a build.

### CODE REVIEW

**Comment by WithoutPants** [comment]
I'm wondering if we should just run the integration tests for all branches. Makes sense when evaluating pull requests. @StashAppDev @Leopere

**Comment by Leopere** [comment]
Yeah, I would say integration tests for everything is nice if it doesn't cost us a colossal workload.

**Comment by WithoutPants** [comment]
Changed so that integration tests are always run.

**Comment by Leopere** [comment]
Ready?

**Comment by WithoutPants** [comment]
`go test` unfortunately does not allow excluding files without build tags. This means that `make it` also runs the non-integration tests. I have clarified this in the Makefile, and removed `make test` from the travis configuration since it is redudant when `make it` is invoked.

Provided the travis build is successful, this should be good to merge.

**Pull request merged**
