### PR TITLE
Freebsd compile errors

### LINKED ISSUE #2429: [Bug Report] Build stash on FreeBSD
**Describe the bug**
Compiling stash on FreeBSD leads to an error.

**To Reproduce**
Run gmake in the stash source folder.

**Expected behavior**
The compilation should succeed.

**Screenshots**
[jmt@clu ~/src/stash]$ gmake
go generate -mod=vendor ./cmd/stash
validation failed: packages.Load: /usr/home/jmt/src/stash/vendor/github.com/kermieisinthehouse/systray/systray_nonwindows.go:13:8: could not import C (no metadata for C)
exit status 1
cmd/stash/main.go:1: running "go": exit status 1
gmake: *** [Makefile:165: generate-backend] Error 1

**Stash Version: (from Settings -> About):**
This error comes with v0.13.0. The version v0.12.0 compiles without any problems.

**Desktop (please complete the following information):**
 - Device: PC
 - OS: FreeBSD 13.0-RELEASE-p10

**Additional context**
The problem comes with the systray library. I managed to disable systray and work arround this problem for the FreeBSD os. But I thing the thrown error is not systray-specific.

### PR DESCRIPTION
**Pull request by kermieisinthehouse**
I believe this is the minimum change necessary to get freebsd to compile. However, I don't know how to build this on my native arch machine.

@isnogudus can you test and see if this builds? `make cross-compile-freebsd`, if you're on x86-64.

Supercedes #2430 
Fixes #2429

### CODE REVIEW

**Comment by isnogudus** [comment]
The code does not compile because the systray lib is missing the FreeBSD fixed.
Below is the error message from the target "cross-compile-freebsd".
```
# github.com/kermieisinthehouse/systray                    
ld: error: undefined symbol: add_or_update_menu_item
>>> referenced by systray@v1.2.4cgo-gcc-prolog:56 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:56)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_add_or_update_menu_item)
                                                           
ld: error: undefined symbol: add_separator
>>> referenced by systray@v1.2.4cgo-gcc-prolog:69 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:69)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_add_separator)
                                                           
ld: error: undefined symbol: hide_menu_item 
>>> referenced by systray@v1.2.4cgo-gcc-prolog:82 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:82)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_hide_menu_item)
                                                           
ld: error: undefined symbol: nativeLoop                    
>>> referenced by systray@v1.2.4cgo-gcc-prolog:97 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:97)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_nativeLoop)
                                                           
ld: error: undefined symbol: quit                          
>>> referenced by systray@v1.2.4cgo-gcc-prolog:112 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:112)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_quit)
                                                           
ld: error: undefined symbol: registerSystray               
>>> referenced by systray@v1.2.4cgo-gcc-prolog:124 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:124)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_registerSystray)
                                                           
ld: error: undefined symbol: setIcon
>>> referenced by systray@v1.2.4cgo-gcc-prolog:139 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:139)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_setIcon)

ld: error: undefined symbol: setTitle
>>> referenced by systray@v1.2.4cgo-gcc-prolog:151 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:151)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_setTitle)

ld: error: undefined symbol: setTooltip
>>> referenced by systray@v1.2.4cgo-gcc-prolog:163 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:163)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_setTooltip)

ld: error: undefined symbol: show_menu_item
>>> referenced by systray@v1.2.4cgo-gcc-prolog:176 (/_/github.com/kermieisinthehouse/systray@v1.2.4cgo-gcc-prolog:176)
>>>               $WORK/b261/_x002.o:(_cgo_7b49007390b5_Cfunc_show_menu_item)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
````
A simple gmake exits with the error:
```
 [jmt@clu ~/src/stash]$ gmake
go generate -mod=vendor ./cmd/stash
validation failed: packages.Load: /usr/home/jmt/src/stash/vendor/github.com/kermieisinthehouse/systray/systray_nonwindows.go:13:8: could not import C (no metadata for C)
/usr/home/jmt/src/stash/internal/desktop/systray_nonlinux.go:48:10: SetTemplateIcon not declared by package systray

exit status 1
cmd/stash/main.go:1: running "go": exit status 1
gmake: *** [Makefile:170: generate-backend] Error 1
[jmt@clu ~/src/stash]$ 
```
So first the systray-lib needs to be fixed. I have written extra files for freebsd in my PR as @bnkai suggested it.

**Comment by kermieisinthehouse** [comment]
Try now. The systray library shouldn't be in the build at all.

**Comment by isnogudus** [comment]
Sorry, it doesn't compile.
```
[jmt@clu ~/src/stash]$ git pull
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 357 bytes | 119.00 KiB/s, done.
From github.com:kermieisinthehouse/stash
 * branch              freebsd-compile-errors -> FETCH_HEAD
Updating 3c190032..d9f91a26
Fast-forward
 internal/desktop/systray_nonlinux.go | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
[jmt@clu ~/src/stash]$ gmake cross-compile-freebsd
go build -o dist/stash-freebsd -mod=vendor -v -tags "sqlite_omit_load_extension osusergo netgo" -trimpath -ldflags "-X 'github.com/stashapp/stash/internal/api.version=v0.13.1-51-gd9f91a26' -X 'github.com/stashapp/stash/internal/api.buildstamp=2022-04-05 08:07:49' -X 'github.com/stashapp/stash/internal/api.githash=d9f91a26' -X 'github.com/stashapp/stash/internal/manager/config.officialBuild=false' -extldflags=-static -s -w " ./cmd/stash
github.com/stashapp/stash/pkg/models
github.com/stashapp/stash/internal/api/urlbuilders
github.com/stashapp/stash/pkg/models/jsonschema
github.com/stashapp/stash/pkg/file
github.com/stashapp/stash/pkg/plugin
github.com/stashapp/stash/pkg/ffmpeg
github.com/stashapp/stash/pkg/studio
github.com/stashapp/stash/pkg/tag
github.com/stashapp/stash/internal/manager/config
github.com/stashapp/stash/pkg/gallery
github.com/stashapp/stash/pkg/movie
github.com/stashapp/stash/pkg/image
github.com/stashapp/stash/pkg/scene
github.com/stashapp/stash/pkg/performer
github.com/stashapp/stash/pkg/sqlite
github.com/stashapp/stash/internal/desktop
github.com/stashapp/stash/pkg/match
github.com/stashapp/stash/internal/dlna
# github.com/stashapp/stash/internal/desktop
internal/desktop/desktop.go:36:3: undefined: startSystray
github.com/stashapp/stash/internal/identify
github.com/stashapp/stash/internal/autotag
github.com/stashapp/stash/pkg/scraper
github.com/stashapp/stash/pkg/scraper/stashbox
gmake: *** [Makefile:63: build] Error 2
[jmt@clu ~/src/stash]$ 
```

**Comment by kermieisinthehouse** [comment]
@isnogudus can you re-pull and re-test? The third time is the charm

**Comment by isnogudus** [comment]
And now it works like a charm ;-)
It compiles without errors and runs on my FreeBSD machine.

**Comment by kermieisinthehouse** [comment]
Fantastic! Merging...

**Pull request merged**
