### PR TITLE
Chinese Simplified Translation

### PR DESCRIPTION
**Pull request by fnoopv**
Add Chinese Simplified Translation

### CODE REVIEW

**Comment by WithoutPants** [comment]
Thanks for the contribution. The localisation system was recently updated, so you may want to redo against an updated version.

**Comment by fnoopv** [comment]
ok

**Comment by Still34** [comment]
The i18n implementation is still being worked on, heavy breaking changes are still to come; please keep that in mind before submitting anything too substantial, thanks!

**Comment by WithoutPants** [comment]
Closing as stale. Please open another against the latest version.

**Pull request closed without merging**
