### PR TITLE
Cross compile for armv7/armv8, raise raspi variant to armv6 (only)

### LINKED ISSUE #585: [Feature] the current Raspberry build is only 32-bit, please provide a build for 64-bit images
The [Ubuntu image is 64-bit](https://ubuntu.com/download/raspberry-pi). Thank you very much.

```
$ file stash
stash: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.2.0, Go BuildID=i1FSHpCNTZ_KpdKf6WzO/wPsfSQrcKjopjAi_8qDM/G2i86PG6zMzbxCddoyW4/vt3BX7ksv3NmGcp-ypN5, BuildID[sha1]=4379e8240db765dfb52d70cba2af4a0bf90b526c, not stripped
$ uname -a
Linux ubuntu 5.4.0-1011-raspi #11-Ubuntu SMP Fri May 8 07:43:33 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by WithoutPants**
Repackaging of #602 to just include the cross-compilation changes. Thanks @hardcore-coder for the contribution.

Fixes #585

### CODE REVIEW

**Comment by WithoutPants** [comment]
Fixes #585

**Comment by Tweeticoats** [comment]
This no longer produces a builds for linux_amd64.
I get the arm6, arm7 and arm8 osx and windows but no linux.

The make file for the docker compiler tags with 3 and latest, the ./scripts/cross-compile.sh uses develop tag.

**Comment by WithoutPants** [comment]
Thanks @Tweeticoats. Should be fixed now.

**Comment by WithoutPants** [comment]
> The make file for the docker compiler tags with 3 and latest, the ./scripts/cross-compile.sh uses develop tag.

To follow up on this, docker hub builds the compiler and tags it with the develop tag, which is why cross-compile.sh uses it. I'll have to change it back.

**Pull request merged**
