### PR TITLE
Make sort filter queries for name case insensitive

### LINKED ISSUE #182: [BUG] Performer page sort order is case-sensitive
Sort order on http://localhost:9999/performers is case-sensitive [A-Z][a-z]. It should be case-insensitive to accommodate performers that go by lowercase usernames among other reasons.

### PR DESCRIPTION
**Pull request by bnkai**
Closes #182 and also works for studios.

### CODE REVIEW

**Comment by Leopere** [comment]
@WithoutPants needs to review but I imagine this is fine.

**Comment by Leopere** [comment]
Adding WIP tag until updates are finished, feel free to remove the WIP tag when adjustments are made and are ready for pushing through testing and squash rebasing.

**Comment by bnkai** [comment]
> We should probably consider changing the name indexing to use `collate nocase` as well.

You mean in the initial creation of  the DB from the migrations or somewhere else?

**Comment by WithoutPants** [comment]
Yes, add a schema migration eventually.

**Comment by WithoutPants** [comment]
Sorry, that comment was more for future reference, not a condition to merge. The code review checked out fine. Haven't been able to test yet.

**Comment by WithoutPants** [comment]
Tests ok. Seems to have a weird inconsistency with upper- and lower-case names in that I got studios in order `ddd`, `DDD`, but performers in `FFFF`, `ffff`. But otherwise seems fine.

**Pull request merged**
