### PR TITLE
Performer and Movie UI fixes and improvements

### PR DESCRIPTION
**Pull request by WithoutPants**
- Sanitises URLs so that a valid URL is created in most cases: 
  - if string starts with a protocol (`http://` or `https://`) then URL is left unchanged
  - otherwise, prepend `https://`
  - for Twitter/Instagram URLs, prepend with `https://twitter.com/` if not present.
- Make gender dropdown consistent in the read-only performer view
- Show URLs as links in Performer and Movie read-only views
- Use duration input for Movie length
- Refactored `TableUtils` to use new `EditableTextUtils`

### CODE REVIEW

**Comment by WithoutPants** [comment]
Fixes #442

**Comment by WithoutPants** [comment]
Added fix for #450 

Fixes #450

**Comment by bnkai** [comment]
The change for the movie duration makes it unable to be unset/cleared.
The `scene->file info->downloaded from` url could also be adjusted? 
The rest test out fine.

**Comment by bnkai** [comment]
can you squeeze this  change also ?
```
diff --git a/ui/v2.5/src/utils/text.ts b/ui/v2.5/src/utils/text.ts
index e8e6c1e..b897c25 100644
--- a/ui/v2.5/src/utils/text.ts
+++ b/ui/v2.5/src/utils/text.ts
@@ -20,7 +20,7 @@ const fileSize = (bytes: number = 0, precision: number = 2) => {
     unit++;
   }
 
-  return `${bytes.toFixed(+precision)} ${Units[unit]}`;
+  return `${count.toFixed(+precision)} ${Units[unit]}`;
 };
 
 const secondsToTimestamp = (seconds: number) => {
```
it fixes the file  size in the scene file info tab

**Comment by WithoutPants** [comment]
* Movie duration field fixed
* Scene URL display fixed
* Fixed `fileSize`

**Pull request merged**
