### PR TITLE
Tasks page refactor

### LINKED ISSUE #908: [Bug Report] Scan options should be persisted
**Describe the bug**
When you check the checkbox ("Set name, date, details from metadata (if present)") inside the (Go to Settings -> Tasks) , it should be 'saved', and stay checked.  However it does not stay checked. Once you exit that page (Go to Settings -> Tasks), then return, the checkbox is not checked.

**To Reproduce**
1. Go to Settings -> Tasks
2. Click on: https://ibb.co/fxL2YSp "Set name, date, details from metadata (if present)"
3. Then exit, click on "Stash" on the top-left, just leave this screen.
4. Then return to: Go to Settings -> Tasks. The checkbox is now unchecked.

**Expected behavior**
When you check the checkbox, it should be 'saved', and stay checked.  However it does not stay checked.

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.
https://ibb.co/fxL2YSp

**Stash Version: (from Settings -> About):**

Version: | v0.3.0-56-g01227ce 
Build hash: | 01227ce
Build time: | 2020-10-27 02:42:13
Latest Version Build Hash: | 01227ce

**Desktop (please complete the following information):**

Windows 10

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by WithoutPants**
Resolves #908

Moves the Scan, Generate and Clean tasks behind dialogs and reorders the tasks page:

image
image
image
image
image

Folder selection is integrated in the dialogs if the selective method was available prior.

Note that the preview generation settings and the overwrite flag have been rolled into the generate dialog so that they are available both on the tasks page and from scene selection.

Todo:
- [x]  save defaults for all tasks

The following should be implemented after this PR is merged:
- add path selection for clean per #1074 
- add path selection for generate
- provide force parameter for transcodes per #1683

### CODE REVIEW

**Comment by WithoutPants** [comment]
Restyled based on feedback.

image

Tasks with a separate ellipsis button will run the task using the default settings if the main button is clicked, and will open the dialog if the ellipsis button is clicked. Where there is no defaults set in the configuration, the dialog will open regardless of which button is clicked. A toast message now appears saving defaults indicating that the default settings will be used when clicking the main button.

Added default setting support for scan, auto tag and generate tasks.

**Comment by WithoutPants** [comment]
Reverted most of the re-styling changes. Separated ellipsis buttons remain, as well as grouping the tasks.

image

**Comment by bnkai** [comment]
- The default settings while being saved correctly in the config file dont  seem to get passed back to the UI.
For example using the scan

Select some options and save

Close the dialog and reopen and you get the first image again


- The paths for the selective scan are not sent to the backend

**Comment by WithoutPants** [comment]
Bloody config refactor biting me again. Should be fixed now.

**Comment by bnkai** [comment]
- The 
`The paths for the selective scan are not sent to the backend`
issue is still present.
Click on a scan/autotag task for example. Select and add a small subdirectory. Click scan/autotag/.... The scanning/taggins goes through all files since the paths are not sent via the graphql request even though they are displayed in the UI dialog

- The default config settings now work ok

- Another minor UI issue
If you `untick` something in the autotag dialog
notclickable
You can't `tick` it back

**Comment by WithoutPants** [comment]
Sorry, didn't read the entire list. The other issues should now be addressed.

**Review by bnkai — APPROVED** [review]

**Pull request merged**
