### PR TITLE
[WIP/RFC] Add rudimentary "watch count" scene attribute

### PR DESCRIPTION
**Pull request by FleetingOrchard**
This is still pretty rudimentary (and mainly intended, at the moment, to spur a bit of discussion as a response to/more functional alternative to #291), but hey, it works. And doesn't seem to trash data on migrations. Success!

Currently it's just an inert number that doesn't auto-increment, or provide a "+1" button (mostly because I can't figure out a good place to put such a thing in the current UI), so don't actually merge this in.

### CODE REVIEW

**Comment by Leopere** [comment]
Even the +1 button would be useful however the one problem is what conditions trigger allowing it's potentially repeated use.

**Comment by WithoutPants** [comment]
A "watch count" field should be something that is automatically incremented when user watches a scene - which is a possible future feature. If we're to add functionality based on #291 then I'd prefer it not be named "watch count".

**Comment by FleetingOrchard** [comment]
I appreciate that, I'm suggesting this as an alternate to 291 -- as to my eye, a watch count more accurately fulfills the actual use case (establishing if something is novel or familiar to the user, and to what degree).

Auto increment just isn't something I've hooked up yet -- I unfortunately didn't have time to do so earlier, and will be adding to this PR as time goes on. I figured it would be worth getting some eyeballs on the idea in the meantime, though, given I'm suggesting here implementing a request by adding something that is, semantically, not that request.

**Comment by Leopere** [comment]
If this tracking stuff is done it should be toggled in settings.

**Comment by WithoutPants** [comment]
#334 has been merged which addresses #291. This could be a good basis for a watch counter functionality, but given the original intention, I'll close this for now.

**Pull request closed without merging**
