### PR TITLE
Add ignore autotag flag

### LINKED ISSUE #2366: [Feature] Autotag Optimizations
Autotag performance currently leaves me unable to run autotag on my image library (just under 14 million images).

I'm requesting some specific optimizations so that autotag can be greatly sped up. Note that the old bulk autotag implementation (sqlite regex based), was much faster, but was less configurable and used more memory.

In scope:
- A checkbox for tags / performers / studios that enables / disables eligibility to autotag. This can reduce the search space considerably AND allow people to run autotag without worrying about pollution of e.g. single name performers.
- Memoization of compiled RE objects during an autotag run to save CPU
- Folding all alias regexes into a single regex: all aliases match the same underlying ID, and assuming they are somewhat similar, we can quickly check them all in one optimized call to regexp. We can generate all of the matching regexes to all aliases, then concat them into a master regex of "REGEX1 | REGEX2 | REGEX3 | ...". The final compiled object will optimize this pretty well, especially if the tags share substrings, like "example tag phrase" and "example tag phrases".
- A dedicated query function for the autotag task that doesn't use a sort by title. On large collections, sqlite sorts use crazy amounts of CPU time, when the order doesn't matter. The internal ROWID sort is consistent enough.
- Indexes for images / scenes tables as necessary for new query

Not in scope: I am unsure of how much time the tag narrowing strategy currently saves. Is tokenizing the string and querying the database really faster than just naively doing all regex comparisons, especially if we only compile them once during task lifetime?

This was partially started in #1927, but it is not necessary to reuse any of it.

I am willing to put a decent bounty on this issue, as it is somewhat large and very useful to me.

### PR DESCRIPTION
**Pull request by WithoutPants**
Resolves #2366 

Adds "Ignore Auto Tag" flag to Performers, Studios and Tags. When true, the object is ignored for autotagging from the tasks page. This will still allow auto-tagging for the object if the Auto Tag button is pressed on the object's page.

Note that the flag is visible on the Edit panel, but not currently on the Details panel. I'm open to changing this.

The flag can be filtered on for queries and has been added to the Performers edit dialog.

### CODE REVIEW

**Review by bnkai — APPROVED** [review]

**Review by kermieisinthehouse — APPROVED** [review]
Tested, thanks!!

**Comment by aaron-typo** [comment]
At least for Tags this does not work: I set the ignore flag to a specific tag and it still gets assigned to scenes when I run autotag from the tasks page.

**Comment by WithoutPants** [comment]
> At least for Tags this does not work: I set the ignore flag to a specific tag and it still gets assigned to scenes when I run autotag from the tasks page.

It's working ok for me. If you can reproduce the issue please raise a bug report issue.

**Comment by aaron-typo** [comment]
> It's working ok for me.

Are aliases of the ignored tag also getting ignored for you?

**Pull request merged**
