### PR TITLE
Disable audio transcode in preview generation

### LINKED ISSUE #1404: [Bug Report] Remove audio from previews and avoid fallback
Stash fails to generate previews on older AVI files and has to try again with the fallback method. 

The error **[mp3float @ 0000022c7b5af4c0] Header missing** is very common with older AVI files.

I wonder why audio is included in the preview files?! Removing audio saves resources and avoids errors.

The log looks like this:

```
[generator] generating sprite image for [...]input.avi 
ffmpeg error when running command <C:\Tools\ffmpeg\bin\ffmpeg.exe -v error -xerror -ss 62.33 -i [...]input.avi  -t 0.75
 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4
 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 generated\tmp\preview_053f1351a064c3e2_001.mp4>:
 [mp3float @ 0000022c7b5af4c0] Header missing
[generator] failed generating scene preview, trying fallback 
```

In our case the error is usually shown twice in ffmpeg's output: once when it checks the mapping (it will continue) and again when it does the decoding (now it will exit due to `-xerror`).

If you use `-map 0` or alternatively `-an` in order to ignore audio it will work.

I am actually not sure why you would want to decode/encode audio into the previews. Maybe I am missing something, it has been a few long days with little sleep.

### PR DESCRIPTION
**Pull request by kermieisinthehouse**
Fixes #1404 

Preview thumbnails are no longer generated with audio. This should provide significant space and bandwidth savings (average 20% on some spot checks). Recommend deleting your generated/screenshots/*.mp4  for large collections and regenerating them.

Before and after mediainfo is included below:

Before:
```
[root@kermie screenshots]# mediainfo 2193126f7720d470.mp4 
General
Complete name                            : 2193126f7720d470.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 732 KiB
Duration                                 : 9 s 264 ms
Overall bit rate                         : 647 kb/s
Writing application                      : Lavf58.29.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 9 s 260 ms
Bit rate                                 : 515 kb/s
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 29.807 FPS
Minimum frame rate                       : 26.347 FPS
Maximum frame rate                       : 29.970 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.075
Stream size                              : 582 KiB (80%)
Writing library                          : x264 core 155 r2917 0a84d98
Encoding settings                        : cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=4 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=10 / rc=crf / mbtree=1 / crf=21.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 9 s 264 ms
Bit rate mode                            : Constant
Bit rate                                 : 122 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 138 KiB (19%)
Default                                  : Yes
Alternate group                          : 1

```

After:

```
[root@hostname screenshots]# mediainfo 2193126f7720d470.mp4 
General
Complete name                            : 2193126f7720d470.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 586 KiB
Duration                                 : 9 s 216 ms
Overall bit rate                         : 521 kb/s
Writing application                      : Lavf58.76.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 9 s 216 ms
Bit rate                                 : 517 kb/s
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 29.970 (29970/1000) FPS
Minimum frame rate                       : 29.455 FPS
Maximum frame rate                       : 29.970 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.075
Stream size                              : 582 KiB (99%)
Writing library                          : x264 core 161 r3048 b86ae3c
Encoding settings                        : cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=4 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=10 / rc=crf / mbtree=1 / crf=21.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC
```

### CODE REVIEW

**Comment by kermieisinthehouse** [comment]
Merging this would address underlying issue of #1281 and would allow us to revert #1340 and enable previews on mobile again!

**Comment by WithoutPants** [comment]
This would disable sound when rolling over previews - we have a specific setting for this:

image

I don't know how many users actually use this, but I'm guessing its more than zero, and they'd probably be unhappy with this. Probably needs to be configurable.

Also, the underlying issue of #1281 was that all videos were autoplaying - that they were all autoplaying with sound was secondary (and I was unable to reproduce that particular issue). #1340 was probably too heavy-handed a fix for it, and we can probably restore autoplaying on very small devices.

**Comment by kermieisinthehouse** [comment]
I don't have the ability to make it togglable as I'm not a go developer. However, I have strong doubts that anybody is using previews with audio. As the default is less than 1 second per segment, how useful can it be?

**Comment by bnkai** [comment]
The option if added should be configurable 
Not a lot of users may want the audio but some definitely need it and we already have a section for those options (so an extra tick wouldnt hurt)
preview_generation

**Comment by bnkai** [comment]
Added a configurable version as a new PR. For any further comments/feedback please use the new #1454 PR
Closing this

**Pull request closed without merging**
