### PR TITLE
Add proper home screen icon for mobile users

### PR DESCRIPTION
**Pull request by Teda1**

### CODE REVIEW

**Comment by kermieisinthehouse** [comment]
I think you'll need to remove the leading slashes to support sub-paths correctly.

**Comment by Teda1** [comment]
Should I make the change for the `shortcut ico` link as well?

**Comment by kermieisinthehouse** [comment]
I'm thinking yes, although that one was on us :)

**Comment by Teda1** [comment]
No worries just wanted to be sure. I'll make the update.

**Review by kermieisinthehouse — APPROVED** [review]

**Pull request merged**
