### PR TITLE
[WIP] Adding empty CONTRIBUTING.md to start #26

### PR DESCRIPTION
**Pull request by Leopere**
Looking to get started on issue #26 we're going to need

### CODE REVIEW

**Comment by WithoutPants** [comment]
[Radarr's contribute guide](https://github.com/Radarr/Radarr/blob/aphrodite/CONTRIBUTING.md) has some nice bits in it. I've made some modifications to it below:

> ### Contributing Code ###
> - If you're adding a new, already requested feature, please comment on Github Issues so work is not duplicated (If you want to add something not already on there, please talk to us first)
> - Rebase from the develop branch, don't merge
> - Make meaningful commits, or squash them
> - Feel free to make a pull request before work is complete, this will let us see where its at and make comments/suggest improvements
> - Reach out to us on the ~~forums or on IRC~~ Discord if you have any questions
> - Add tests (unit/integration)
> - Commit with *nix line endings for consistency (We checkout Windows and commit *nix)
> - One feature/bug fix per pull request to keep things clean and easy to understand
> - Follow existing code formatting conventions: tabs in go files, 2 spaces for tsx files
> 
> ### Pull Requesting ###
> - Only make pull requests to develop, never master, if you make a PR to master we'll comment on it and close it
> - You're probably going to get some comments or questions from us, they will be to ensure consistency and maintainability
> - We'll try to respond to pull requests as soon as possible, if its been a day or two, please reach out to us, we may have missed it
> - Each PR should come from its own [feature branch](http://martinfowler.com/bliki/FeatureBranch.html) not develop in your fork, it should have a meaningful branch name (what is being added/fixed)
>   - new-feature (Good)
>   - fix-bug (Good)
>   - patch (Bad)
>   - develop (Bad)

We can probably add something about running `go fmt` on changed files.

This file should also define and document the workflow we use (whenever we settle on something).

**Comment by Leopere** [comment]
I agree with most of it but not really sure if I care if it's on it's own feature branch. I don't really want to get that fickle we already have referential commentary on the github PRs.

**Comment by WithoutPants** [comment]
I think it's probably more of a best practise kind of thing. It's not grounds for rejecting a PR, but for someone new to the project, it would be good advice to give.

**Comment by Leopere** [comment]
Good idea, we should have an opening clause mentioning that its just guidelines that should be adhered to as best as possible.

**Comment by Leopere** [comment]
Gonna close this until we can revisit it.

**Pull request closed without merging**
