### PR TITLE
Ffmpeg changes

### PR DESCRIPTION
**Pull request by ExceptionalError**
- Added output of error message from ffmpeg
- modified args for screenshot creation

### CODE REVIEW

**Comment by bnkai** [comment]
The quoted filename path breaks the linux build just like #117

**Comment by Leopere** [comment]
Breaking, must be fixed.

**Comment by ExceptionalError** [comment]
I reverted the changes so that the only change should now be the output of the error message of ffmpeg

**Comment by Leopere** [comment]
If you want to ship other fixes please I encourage you to start a different PR.  Otherwise since this builds I'll tag @bnkai to ask them to test and let me know if it's still functional in Linux.  Neither of us can test in Windows so it's hard to merge some of these changes.  I honestly didn't even know there was a windows build of this until a few days ago.

**Comment by ExceptionalError** [comment]
> If you want to ship other fixes please I encourage you to start a different PR.

Yes - sorry. This was a mixup when creating the pr on my side.

**Comment by Leopere** [comment]
Now just waiting on review from @WithoutPants and @bnkai and then I can merge this.

**Comment by bnkai** [comment]
I can't see how a simple print breaks anything. It compiles ok but i don't have an easy way to force an error and check it as i said in #48 .
@ExceptionalError have you tried it or you need the binary to test it?

**Comment by Leopere** [comment]
I guess we can merge this and just wait and see what bug reports roll in after given that the build isn't breaking and the binary is running still.   Merging...

**Pull request merged**
