### PR TITLE
Add autorefresh of task status to tasks page

### PR DESCRIPTION
**Pull request by ueaslsef**

### CODE REVIEW

**Comment by Leopere** [comment]
It could be a reasonable value add, but I feel there has to be a better way than just to refresh the page on an interval breaking the user's interaction flow.

**Comment by bnkai** [comment]
It's not exactly refresh page @Leopere  , it more of a pooling of the tasks status...
@ueaslsef was there something wrong , not optimal with the current implementation ?

**Comment by WithoutPants** [comment]
This should not be necessary. The websocket subscription should be automatically updating when tasks start and finish.

**Comment by Leopere** [comment]
> This should not be necessary. The websocket subscription should be automatically updating when tasks start and finish.

Perhaps the interface is failing in just indicating that there is progress being made.  Perhaps we should tweak the interface in some way to indicate that the app is doing something and actually progressing in some way.

**Comment by ueaslsef** [comment]
The ui never updated by itself, so this was the quick and dirty fix. No, it does not reload the page, just poll the endpoint every 2.5 seconds until it is idle again.

**Comment by WithoutPants** [comment]
> The ui never updated by itself, so this was the quick and dirty fix. No, it does not reload the page, just poll the endpoint every 2.5 seconds until it is idle again.

In that case, an issue should be raised detailing the bug. There should be no need to poll the endpoint when we already have a websocket connection and graphql subscription that handles task updates.

**Comment by bnkai** [comment]
I don't seem to have the issue , the tasks seem to update the status bar ok.
Maybe close and open an issue as @WithoutPants mentioned to reproduce the "bug" if possible ?

**Comment by Leopere** [comment]
Is this redundant now? 

Closing unless is not redundant then feel free to re-open.

**Comment by ueaslsef** [comment]
Yes it is, sorry for beeing absent for so long.

**Pull request closed without merging**
