### PR TITLE
Allow unsetting of rating, studio, gallery

### LINKED ISSUE #127: Unable to remove studio from scene
I accidentally associatated a studio with a particular studio. It is not possible to select None as an option for studio if you have already selected a studio. Need to add a None option.

### PR DESCRIPTION
**Pull request by WithoutPants**
Fixes #127 

Allows unsetting of rating, studio and gallery in a scene.

Also fixes unsetting the sceneID value on the scene's old gallery when the scene's gallery is changed.

### CODE REVIEW

**Comment by bnkai** [comment]
@WithoutPants even setting the rating with this build messes the scene's details
Everything in the file details tab turns to null File Size Duration Dimensions ....

**Comment by bnkai** [comment]
update : even unsetting a gallery has the same issues

**Comment by Leopere** [comment]
Can we get an update on this PR it would be awesome to have this feature fixed in the main build.

**Comment by bnkai** [comment]
Patience @Leopere  i had a quick look but i can't figure out where it goes wrong.
Hopefully Withoutpants will figure it out.

**Comment by Leopere** [comment]
If you can't tell I work from home.  When I get a second I check my emails. I didn't realize the timestamp when I'd posted so rather than deleting it I just let it fly.

**Comment by WithoutPants** [comment]
I had time to develop the original change, but little time to investigate fixing it. Anyway, the issue @bnkai raised should now be fixed. However, this is still WIP since rating keeps resetting to the old value in the UI when the scene is saved, so I still need to fix that.

**Comment by WithoutPants** [comment]
Ready for testing/review.

**Comment by bnkai** [comment]
All tested ok and working

**Comment by Leopere** [comment]
Thanks for everyone's hard work on this.

**Pull request merged**
