### PR TITLE
Add title, rating, o-counter to image lightbox

### PR DESCRIPTION
**Pull request by WithoutPants**
See screenshots. Allows setting rating and o-counter. The title is clickable to navigate to the image page.

image
image

### CODE REVIEW

**Comment by WithoutPants** [comment]
Per Discord feedback, rearranged the controls so that the o-counter is on top. I also made the height of the bottom bar a little bigger to make it a little less condensed.

image

**Comment by bnkai** [comment]
I get a very weird error when cycling back from the first image of a gallery collection/ images page to the last
- Go to the images page in WALL mode (1st page)
- Click any of the images
- Try to navigate back 
- When you get past the first image(last image of your images) you get this error
```
Something went wrong.
TypeError: Ae is undefined
Pb@http://localhost:9998/assets/index.7c179a30.js:1773:106951 Xb@http://localhost:9998/assets/index.7c179a30.js:1773:116721 Jd@http://localhost:9998/assets/index.7c179a30.js:1:2481 Sb@http://localhost:9998/assets/index.7c179a30.js:1773:77281 t@http://localhost:9998/assets/vendor.9722a44c.js:149:3839 h9@http://localhost:9998/assets/index.7c179a30.js:1785:52414 q4@http://localhost:9998/assets/index.7c179a30.js:1802:44487 DYe@http://localhost:9998/assets/vendor.9722a44c.js:85:2523 t@http://localhost:9998/assets/vendor.9722a44c.js:114:3696 t@http://localhost:9998/assets/vendor.9722a44c.js:114:10004
```

**Comment by WithoutPants** [comment]
> I get a very weird error when cycling back from the first image of a gallery collection/ images page to the last
> 
> * Go to the images page in WALL mode (1st page)
> * Click any of the images
> * Try to navigate back
> * When you get past the first image(so to the last image of your images) you get this error

I'm not able to reproduce this with Chrome or Firefox.

**Comment by bnkai** [comment]
Update
- Issue is present in firefox/chrome/chromium in linux. The error message when replicating for  galleries with the chromium based browsers is the below
error-message
Browsers used
error-browsers
- The issue does not appear to be PR related. I was testing against builds from PRs #2257,  #2234  where the issue is not present. Retested today with latest dev and the issue is present there too. So NOT PR related after all

**Review by bnkai — APPROVED** [review]

**Comment by kermieisinthehouse** [comment]
On firefox, webkit, and chrome, updates to the o-counter are delayed until some other events are processed (like zooming the image, clicking other buttons, etc.) There's an event loop issue somewhere

**Comment by WithoutPants** [comment]
> On firefox, webkit, and chrome, updates to the o-counter are delayed until some other events are processed (like zooming the image, clicking other buttons, etc.) There's an event loop issue somewhere

I'm not able to reproduce this on Firefox or Chrome on Windows or Linux.

**Pull request merged**
