### PR TITLE
Upgrade react-select version

### PR DESCRIPTION
**Pull request by JackDawson94**
Upgrade react-select to major version 5
https://react-select.com/upgrade#from-v4-to-v5

### CODE REVIEW

**Comment by DingDongSoLong4** [comment]
I've also done this migration as part of #3123.

**Comment by JackDawson94** [comment]
@DingDongSoLong4  happy to cancel this PR if yours goes through 😊
By the way, do you have an automated way to perform these upgrades ? I see you did a lot of them in that PR

**Comment by DingDongSoLong4** [comment]
Nope, did them all manually - many changelogs were read over many days. I don't think any of the minor/patch upgrades needed changes (semver is amazing), and a lot of the rest was quite tedious but mostly straightforward.

**Comment by JackDawson94** [comment]
Cancelled because it's already included in https://github.com/stashapp/stash/pull/3123

**Pull request closed without merging**
