### PR TITLE
fixed performers not being order by name and gender

### LINKED ISSUE #498: [Bug Report] Performers not being ordered by name inside of scene
**Describe the bug**
The performers are not being ordered by name inside of the scene detail and preview box.

**To Reproduce**
1. Create two performers, the first one with a Z and the first with a A.
2. Click on a scene with those two performers.
3. Click on Performers.
4. The Performers are ordered by Id and not the Name.

**Expected behavior**
The performers should be ordered by name

### LINKED ISSUE #643: [Feature] List female performers before male performers
**Is your feature request related to a problem? Please describe.**
Often the information about which female performers are in a scene are more important than which male performers. Therefore female performers should be listed first.

**Describe the solution you'd like**
Instead pure alphabetical sorting on the performer popup and scene sidepanel sort ts > female > male.

**Describe alternatives you've considered**
An option with sorting settings? I think it's overkill though.

### PR DESCRIPTION
**Pull request by julien0221**
I fixed the bug when performers are not being order by name. And I added as well order by gender.
Resolves #498 Resolves #643

### CODE REVIEW

**Comment by peolic** [comment]
This works.

But if I may add, id does not fully resolve #643:
Simply ordering by `performers.gender` (ascending by default) means that this will be the order of performers on the scenes:
```
FEMALE
INTERSEX
MALE
NON_BINARY
TRANSGENDER_FEMALE
TRANSGENDER_MALE
```
Notice that transgenders are at the bottom.

I'm no SQL expert but, one solution I found is this: https://stackoverflow.com/a/3303876
**However, I do agree** that at that point a custom sort order configurable by the user is the ultimate solution.

**Comment by julien0221** [comment]
my bad you are right, so if someone can agree about which order we want please? and I will do the changes.
FEMALE > TRANSGENDER_FEMALE > MALE > TRANSGENDER_MALE > INTERSEX > NON_BINARY, maybe?

**Comment by julien0221** [comment]
I just pushed a fix for the order I mentionned.

**Comment by WithoutPants** [comment]
This is a UI presentation issue, and should therefore (imo) be addressed in the UI, not enforced in the backend.

**Comment by WithoutPants** [comment]
Closing in favour of #1294

**Pull request closed without merging**
