### PR TITLE
Add divider to gallery tab

### PR DESCRIPTION
**Pull request by Teda1**
This pull request makes the gallery tab collapsable so gallery images can take up the full window width.

Uncollapsed:
Screenshot 2023-03-05 093707

Collapsed:
Screenshot 2023-03-05 094134

### CODE REVIEW

**Comment by WithoutPants** [comment]
I think the image page divider is of pretty limited use. A better option would be to click the image to view it fullscreen. Gallery divider looks good.

**Comment by Teda1** [comment]
Yeah, I questioned the practicality of the image divider after pushing that change. I'll remove it.

**Comment by JanJastrow** [comment]
Suggestion: also add the `,` shortcut to colapse/open it.

**Comment by Teda1** [comment]
I can include that shortcut in https://github.com/stashapp/stash/pull/3514.

**Pull request merged**
