### PR TITLE
play monitoring improvement

### PR DESCRIPTION
**Pull request by cj12312021**
This pull request updates the play monitoring code to detect video buffering and not count that towards the total play duration.

### CODE REVIEW

**Comment by cj12312021** [comment]
My latest push ensures that Track Activity is enabled by default.

**Comment by AdultSun** [comment]
Any chance this PR could also add tracking activity through DLNA? I don't know how difficult that would be.

https://github.com/stashapp/stash/issues/3681

**Comment by cj12312021** [comment]
DLNA doesn't use the front-end VideoJS player, so tracking activity there would likely not be done with the typescript code. So, the code would be completely separate from what we currently have. I have had it in mind to look into support on that side. I just need to spend some time understanding how playback works when using the DLNA service.

**Comment by AdultSun** [comment]
Thanks, I don't mean to pressure you if it's outside of the scope of your PR so no worries if you don't get to it. I just wanted to bring it up in case it was an easy add while you're working in this area.

**Comment by cj12312021** [comment]
No worries. I'm also interested in DLNA support, so you better believe I'd have a pull request out for the DLNA watch activity tracking once I've sorted out the details.

**Comment by WithoutPants** [comment]
> My latest push ensures that Track Activity is enabled by default.

If this changes existing systems, this will require an accompanying release note.

**Comment by cj12312021** [comment]
The update should only affect affect Stash configs. But I'll pull that change into a separate PR to avoid complicating the delivery of the play monitoring improvement.

**Pull request merged**
