### PR TITLE
Add support for the Handy APIv2

### PR DESCRIPTION
**Pull request by chetbrinko**
Docs: https://staging.handyfeeling.com/api/handy/v2/docs/
Ref: https://github.com/defucilis/thehandy

Update axios to 0.24.0 due to a security update

Progress on https://github.com/stashapp/stash/issues/1376

I've updated https://github.com/defucilis/thehandy with the change https://github.com/defucilis/thehandy/pull/2 because the class HandyUtils wasn't exported, which is why this is a Draft PR. In order to test/verify the change you will need to use my branch until it is merged upstream

Also I added support for the following funscript features:
 - inverted flag
 - range argument

### CODE REVIEW

**Comment by chetbrinko** [comment]
@UnluckyChemical765 btw thank you for your earlier work on which this is based

**Comment by inventiv3919** [comment]
Do you have a docker container of this by any chance?

**Comment by chetbrinko** [comment]
@inventiv3919 https://hub.docker.com/r/chetbrinko/stash_handyv2

**Comment by kermieisinthehouse** [comment]
Testing is welcome, as none of the devs have the hardware. We can only review the code, not the functionality

**Comment by inventiv3919** [comment]
Trying to launch the docker container gives error: standard_init_linux.go:230: exec user process caused: exec format

**Comment by chetbrinko** [comment]
@inventiv3919 sorry, the docker image was built for arm - i forced it to amd64 for you so if you repull it should work - i can't verify easily as i'm on arm

**Comment by chetbrinko** [comment]
@kermieisinthehouse understood - all I can say is "works on my machine/hardware" from since I opened the PR - hopefully @inventiv3919 can provide external validation.

**Comment by inventiv3919** [comment]
@chetbrinko thanks :) I'll try test it out later today

**Comment by inventiv3919** [comment]
Just fired it up and watched a few videos, seems to work perfectly so far. I was able to change my funscript offset from -655 down to -50, definitely a big improvement

**Comment by inventiv3919** [comment]
@chetbrinko @kermieisinthehouse  I've been using it all week with no issues :)

**Comment by kermieisinthehouse** [comment]
Given how simple the bindings are, we could probably host the repo under the stashapp org.

**Comment by chetbrinko** [comment]
@kermieisinthehouse feel free to fork my fork into the org, if you please. Happy to be added as a contributor to maintain it

**Comment by WithoutPants** [comment]
Is there any reason we can't use the fork as-is until it is patched upstream?

**Comment by WithoutPants** [comment]
I have update to sync with the develop branch. I've changed it to use `thehandy 1.0.3` package and re-implemented `uploadCsv` so that `HandyUtils` does not need to be exported for this. Once the pending PR is merged upstream, we can change the code to reference that instead.

This will need a retest from @chetbrinko, @inventiv3919 or someone else with the necessary hardware. Be aware that the shift to videojs may have introduced issues with interactive functionality, so if bugs do occur it may be worth comparing it with the current development build.

**Comment by WithoutPants** [comment]
@inventiv3919 I made a docker image for you to test with: `withoutpants/stash:handyv2`
(repo here: https://hub.docker.com/repository/docker/withoutpants/stash)

**Comment by inventiv3919** [comment]
Thanks for making the docker image @WithoutPants 

The shift to videojs has indeed introduced an issue: the handy connects and syncs fine and responds accordingly when the stash player is paused/resumed however seeking ahead/back does not update the handy and there doesn't appear to be a way to resync it without reloading the page and not skipping through at all. 

@chetbrinko may need to update the PR so that videojs exposes the current timepoint to the handyapi

**Comment by WithoutPants** [comment]
> Thanks for making the docker image @WithoutPants
> 
> The shift to videojs has indeed introduced an issue: the handy connects and syncs fine and responds accordingly when the stash player is paused/resumed however seeking ahead/back does not update the handy and there doesn't appear to be a way to resync it without reloading the page and not skipping through at all.
> 
> @chetbrinko may need to update the PR so that videojs exposes the current timepoint to the handyapi

Pausing the video and then playing again does not sync it again?

**Comment by inventiv3919** [comment]
It does not. It pauses it but when I click play again the handy continues without resyncing

**Comment by WithoutPants** [comment]
Are you able to test while looking at the browser development console?

Under the network tab, there should be requests for `hssp/play` and `hssp/stop`. When the video starts or seeks, I expect a call to `hssp/play` with `estimatedServerTime` and `startTime` filled in.

Can you verify what requests are sent when starting, pausing, seeking and pausing after seeking?

**Comment by inventiv3919** [comment]
Ok I think it's a problem with Samsung internet when I used chrome on my laptop everything except the quick skip buttons worked (and then it resynced by pausing then resuming). Seems to also be working on chrome for Android so I'll switch to that browser. Sorry for wasting your time

**Comment by WithoutPants** [comment]
So this PR is good to go? Not sure why the skip buttons aren't working correctly.

**Comment by inventiv3919** [comment]
I'd say so yeah, the skip buttons aren't a big deal

**Pull request merged**
