### PR TITLE
Allow the use of fully qualified paths for Python.

### PR DESCRIPTION
**Pull request by dsully**

### CODE REVIEW

**Review by kermieisinthehouse — APPROVED** [review]

**Review by peolic — CHANGES_REQUESTED** [review]
Haven't tested, but I believe this change would break the current way script scrapers (and possibly raw plugins) use this.
In any case (instead of this change), you should be able to use Python Path setting, which should be in the System tab of the settings, or `python_path` in the `config.yml`.

**Comment by dsully** [comment]
@peolic That's the problem though. If a fully qualified Python path is specified, such as:

`/home/linuxbrew/.linuxbrew/bin/python3`

Then `isPythonCommand` will return false, since it's comparing that fully qualified path against `"python" || "python3"`

**Comment by peolic** [comment]
I'll explain again.

In the scraper/plugin you define, **you use either `python` or `python3` as the first argument**.
Basically makes it so the files are shareable with minimal to no modification necessary, like on [CommunityScrapers](https://github.com/stashapp/CommunityScrapers) and [CommunityPlugins](https://github.com/stashapp/CommunityScripts).

In [__*your own* Stash configuration__](https://user-images.githubusercontent.com/66393006/168477008-7a44ff83-4e8b-499d-ae6c-fbd3576bc212.png),
you can set a fully qualified path to the Python executable, so it uses it whenever it detects a request to run Python (using `isPythonCommand`),
or leave it blank for Stash to find it from `PATH`.

For example, the code for script scraper execution:
https://github.com/stashapp/stash/blob/v0.14.0/pkg/scraper/script.go#L35-L53

```go
if python.IsPythonCommand(command[0]) {
```
would be true when the first argument of the script scraper definition is `python` || `python3`

next,
```go
		pythonPath := s.globalConfig.GetPythonPath()
		var p *python.Python
		if pythonPath != "" {
			p = python.New(pythonPath)
```
will get the Python Path from your config, and use that if it's defined.

related: #2290 #2409

**Comment by dsully** [comment]
That's not the behavior I'm seeing. If I set Python to a fully qualified path in settings, scripts are not launched properly.

**Comment by WithoutPants** [comment]
peolic is correct. `IsPythonCommand` is intended to be used for the plugin and scraper code to identify if the script is using python. It's entire purpose is to avoid having to put in the full path to python in the plugin/scraper config in the first place. If python isn't being resolved correctly after setting the python path in your stash configuration, then please raise a bug issue for it. This isn't the correct solution.

**Pull request closed without merging**
