### PR TITLE
Studio aliases

### LINKED ISSUE #1625: [Feature] Studio aliases
**Is your feature request related to a problem? Please describe.**
Some studios have alternate names or spellings, and some studios have changed their name over the years. Since each studio entry can can only have one name, this limits their auto-tagging scope. The end-user either has to make a duplicate studio entry with the alternate/defunct name, or tag files of said studio manually.

**Describe the solution you'd like**
Create the capability for the end-user to add studio alias names that will be part of the auto-tagging process for studios.

An example use-case is the website studio PornWorld formerly called DDF Networks, and often denoted in filenames as DDF.

- Main studio: PornWorld
  - Alias: ddf
  - Alias: ddfnetwork

### PR DESCRIPTION
**Pull request by gitgiggety**
Add support for studio aliases. Updates the GrapQL API, auto tagging, filename parsing, importing/exporting, matching during scraping, etc.

Fixes #1625

### CODE REVIEW

**Comment by WithoutPants** [comment]
The auto tagger doesn't match on studio aliases when running from `Tasks -> Autotag`. I managed to fix it with this addition in `autotag/studio.go`:
```
	for _, c := range candidates {
		matches := false
		if nameMatchesPath(c.Name.String, path) {
			matches = true
		}

		if !matches {
			aliases, err := reader.GetAliases(c.ID)
			if err != nil {
				return nil, err
			}
			for _, alias := range aliases {
				if nameMatchesPath(alias, path) {
					matches = true
					break
				}
			}
		}

		if matches {
			ret = append(ret, c)
		}
	}
```

It requires an update to the unit test as well, which is why I haven't just done it myself.

**Comment by gitgiggety** [comment]
Hmm, good find. I probably didn't notice because I have the files structured in folders by studio, so to reproduce I had to remove the (full) studio name from path.
_But_ such code isn't in the tag code either (which I copy pasted the code from). So does that work properly or does that have the same bug?

I fixed the unit tests such that they pass. It might be desirable to copy/paste the test method and modify it so the name doesn't match and the alias would match?

Also rebased on top of current develop branch (fixes conflict in `scrapers/matcher.go`)

**Review by WithoutPants — APPROVED** [review]

**Comment by gitgiggety** [comment]
@WithoutPants you can be lucky I was using `git push --force-with-lease` :). I just rebased this on develop myself (obviously to fix migration as well). So I almost overwrote your changes / merge.

**Comment by WithoutPants** [comment]
😬 It wouldn't have been a big deal anyway :)

**Pull request merged**
