### PR TITLE
Fix tag hierarchy validation

### PR DESCRIPTION
**Pull request by 7dJx1qP**
An attempt to fix https://github.com/stashapp/stash/issues/1754

Updates were made based on a conversation with @SmallCoccinelle in Discord.

The first thing I noticed while investigating the tag hierarchy was that in `tag.go` the queries for FindAllAncestors and FindAllDescendants were returning tags that weren't ancestors/descendents of the tag being checked. I think it was returning all descendents of all ancestors and all ancestors of all descendents. Removing the last union select from each query seems to address that. This change alone actually fixes the bugged scenario described in the issue https://github.com/stashapp/stash/issues/1754#issuecomment-924620432

I then noticed that taking the test scenario and attempting to add the D-> A relationship was returning an error. The rest of the code changes are to address that.

The end result is intended to just allow for any tag hierarchy that is a DAG.

The changes break the current tests and I haven't check yet if MergeHierarchy works properly.

### CODE REVIEW

**Comment by 7dJx1qP** [comment]
I updated the recursive query to include the tag path so it can be displayed in the error message. It should help users get an idea of why an update is rejected.
image

For this change I created a TagPath model which is just a Tag model with another Path field, but it breaks a bunch of tests. Is there a better way to implement returning a tag model + path from the query?

**Comment by 7dJx1qP** [comment]
Added logging the save and merge errors
image

**Comment by SmallCoccinelle** [comment]
This is pushing in the right direction I think.

**Comment by 7dJx1qP** [comment]
I don't think I'll be adding to this unless something needs fixing. The tag UI could use improvement but I think that's outside the scope of this PR. And I don't know if I could successfully implement a more significant change anyway.

**Comment by WithoutPants** [comment]
> One of the key things in a fix here is to establish the rules of the tag hierarchy. Those rules define a good test set, and also defines if a future issue is a bug or not. Some observations:

The only rule established was that there can be no cycles. We allow tags to have multiple parents.

**Comment by WithoutPants** [comment]
There are a few issues in this PR and in the validation code - not least that it's not being triggered when creating tags. I'm going to spend some time refactoring and testing and will push to this branch.

**Comment by 7dJx1qP** [comment]
It looks like no validation on tag creation is a bug that affects the current release as well. I knew that the tag hierarchy described in https://github.com/stashapp/stash/issues/1754 worked when creating tags, but I just incorrectly assumed it was due to the validation working properly when tags were created and not working when editing. Good catch.

This means users might have already introduced loops into their hierarchy without knowing it and would only find out if they went back to edit the tag. Maybe on migration or startup there should be a validation run on the whole hierarchy to log/alert the user of any existing loops?

**Comment by WithoutPants** [comment]
I'm content to leave it as a latent issue for the moment. It will only come up when the user tries to edit a tag in the hiearchy, at which point they will need to correct it, but I think it's likely to be a rare issue and I'm not keen on adding a heap of code to detect it.

**Pull request merged**
