### PR TITLE
Remove styling from #performer-page div

### PR DESCRIPTION
**Pull request by dogwithakeyboard**
The margins on the performer page are indented by 15px which is interferring with the position of the scrollbar. The other styling doesn't appear to have a purpose in the current version.

### CODE REVIEW

**Comment by Teda1** [comment]
Which version of Stash are you on? The 15px row margins should no longer be active with the CSS written in the performer page divider work.

**Comment by Teda1** [comment]
My mistake, I misunderstood the pull request.

**Review by Teda1 — APPROVED** [review]
It wasn't clear to me either what purpose that CSS served. Both the desktop and mobile pages function properly without it from my testing.

**Comment by dogwithakeyboard** [comment]
I guess it's vestigal from some ye olde stash.

**Pull request merged**
