### PR TITLE
Add Delete Scene button

### LINKED ISSUE #76: [Request] Delete-Buttons in Overview and Detail-Page
This is kind of connected to: https://github.com/stashapp/stash/issues/63  
  
It would be really handy in my opinion to have little buttons by the side of the videos in the overview and especially in the detail-page where you watch a video so that you can delete a certain scene directly from stashapp-database _and_ also from filesystem.
Maybe with an option in the settings-menu if data should be deleted in filesystem or not.  

With implementing this one could manage the collection through stashapp and without using a cron to search for deleted scenes and then delete them one by one from database manually.   
  
I use stashapp remotely on a machine which collects scenes for me automatically and i use it to check the downloaded content out and for this/my usecase also delete-buttons in the scene-overview would be nice and way quicker with sorting the collection.

### PR DESCRIPTION
**Pull request by WithoutPants**
Resolves #76, #8 (with the #100 PR) and should help with #63 

Adds a delete button to the edit scene panel. Clicking this button shows a dialog to confirm the delete operation, while also giving the option to delete the file from the filesystem (defaulting to false), and to delete generated files (defaulting to true).

When deleting the files from the filesystem, if any of the file deletions fail, then an error is logged, but does not prevent the operation from completing.

### CODE REVIEW

**Comment by echo6ix** [comment]
On the Windows build:

Sometimes deleting a scene that had just been viewed deletes everything but the video file. This also happens when trying to manually delete a video from the file system that was just viewed in Stash, with the error, "File in use. This action cannot be completed because the file is open in stash.exe. Close the file and try again"

**Comment by Leopere** [comment]
I am still receiving these conflicts.

## Conflicting files
pkg/api/resolver_mutation_scene.go
pkg/models/generated_exec.go
pkg/models/generated_models.go

**Comment by WithoutPants** [comment]
The delete function now closes running streams/encodes before attempting to delete the file. This should resolve the issue identified by @echo6ix 

Leaving this in WIP until #146 is merged, as I will clean up some repeated code before it will be ready to merge.

**Comment by bnkai** [comment]
I'll test after that then

**Comment by WithoutPants** [comment]
Unified the common code between this PR and #146. As a result, the delete scene and clean functionality may need a quick verification test. Both appear to be testing ok on my end.

**Comment by bnkai** [comment]
Everything checks out ok for me too.

**Comment by Leopere** [comment]
Verified by @WithoutPants and @bnkai merging

**Pull request merged**
