### PR TITLE
HTTP streaming overhaul

### LINKED ISSUE #2609: [Bug Report] Transcoding options vanish and does not work on ipad
**Describe the bug**
The transcoding options are not working on ipad.

**To Reproduce**
View a video on ipad and change the transcoding. Than the waiting circle appears and after a while the video plays in the old resolution without transcoding. Further more the selected options vanishes from the transcoding menu.

**Expected behavior**
The movie should be transcoded like on desktop

**Screenshots**

**Stash Version: (from Settings -> About):**
The bug was introduced with v0.15.0. On v0.14.0 everything worked as expected.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox
 - actual version

**Smartphone (please complete the following information):**
 - Device: ipad 6
 - OS: iPadOS 15.4.1
 - Browser safari, chrome, firefox, duck duck go browser
 - actual versions

**Additional context**

### LINKED ISSUE #2688: Transcoding options are not available on older video formats.
**Describe the bug**
When I try to watch an older video, it does not give me transcoding options. I have tried this on my iphone with safari, chrome and edge. The video is in WMV, but this works when I try and newer mp4 video. No issues when I use edge on my pc. Is this a known bug with the video player?
**To Reproduce**
1. Go to 'Scenes'
2. Click on 'a scene that is WMV or another older format'
3. Scroll down to 'the gear icon'
4. See error: None of the transcoding options seem to show up.

**Expected behavior**
Expected behavior is to see the various transcoding options.

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Stash Version: (from Settings -> About):**
0.15

**Tablet (please complete the following information):**
 - Device: iPad Pro (3rd Generation)
 - OS: iPadOS 15.5
 - Browser: Safari, Chrome & Edge

### LINKED ISSUE #2831: [Feature] Better support for WMV/MKV
**Is your feature request related to a problem? Please describe.**
WMV and MKV need forever to load, sometimes don’t work at all. Fast forwarding/skipping in the video is nearly unusable.
This changed since the use of video.js, before it worked much better (at least on iOS)

**Describe the solution you'd like**
Bring back JW Player for MKV/WMV or make it possible to start an external app (mobile) like VLC from the stream URL.

Perhaps if the user could modify the link, it could work. For iOS you should be able to call VLC directly (not tested): vlc-x-callback://x-callback-url/ACTION?url=...&PARAMETER=... 
You can also start intents like that on Android. Not a nice solution, since configuration is needed for it

**Describe alternatives you've considered**
Copying the stream URL to VLC, which works, but is not great regarding the usability. Converting all videos would be a solution as well, but there are to many videos

### LINKED ISSUE #2901: [Bug Report] Incorrect mime types for transcoded scene streams
**Describe the bug**
Transcoded streams have incorrect mime type `video/mp4` instead of for instance `video/webm`

**To Reproduce**
Run query:
```
{
  findScene(id:523){
    sceneStreams{url, mime_type},
  }
}
```
Response:
```
{
    "data": {
      "findScene": {
        "sceneStreams": [
          {
            "url": "http://192.168.66.6:9999/scene/523/stream",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.mkv",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.webm?resolution=FOUR_K",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.webm?resolution=FULL_HD",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.webm?resolution=STANDARD_HD",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.webm?resolution=STANDARD",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.webm?resolution=LOW",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.mp4?resolution=FOUR_K",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.mp4?resolution=FULL_HD",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.mp4?resolution=STANDARD_HD",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.mp4?resolution=STANDARD",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.mp4?resolution=LOW",
            "mime_type": "video/mp4"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.webm",
            "mime_type": "video/webm"
          },
          {
            "url": "http://192.168.66.6:9999/scene/523/stream.m3u8",
            "mime_type": "application/vnd.apple.mpegurl"
          }
        ]
      }
    }
  }
```
Base webm stream has correct `mime_type` but the transcoded ones, e.g. `http://192.168.66.6:9999/scene/523/stream.webm?resolution=STANDARD_HD` has a different mime type.

**Expected behavior**
`mime_type` should probably be the same for all webm streams. Also mkv should have `video/x-matroska`

**Stash Version: (from Settings -> About):**
0.16.1

### LINKED ISSUE #2934: [Bug Report] Default Player Resolution for HEVC scenes
**Describe the bug**
Currently, when playing HEVC videos, the default selected resolution is incorrect. For a 1080p scene for example, I've noticed "webm low (240p)" being selected by default. This only seems to occur on HEVC videos from what I've noticed. When you play a AVC video, it selects "Direct stream" as default, which isn't available for HEVC which is what I believe to be the cause.

I cannot confirm that this is the same on other codecs such as VP9 or VP8.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a video that uses the HEVC codec
2. Play the video
3. The video will be played in a lower resolution instead of its full quality (if not, perhaps try a different video)

**Expected behaviour**
The video should always play at its full resolution and not default to a lower quality.

**Stash Version:** 3fa7b470 (built from develop branch)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H1 (Build 19043.1889)
 - Browser: Vivaldi (Chromium browser, however confirmed to exist in Chrome as well)
 - Version: 5.4.2753.51 (Stable channel) (64-bit)

### PR DESCRIPTION
**Pull request by DingDongSoLong4**
This is the overhauled HLS/DASH streaming implementation split out from what was in #3020 originally.

From before:

This replaces the transcoding implementation to only use HTTP streaming formats (HLS for H264 and DASH for VP9), based off of #2322. The videojs player doesn't support VP9 with DASH natively, so videojs-contrib-dash (using dash.js) is needed.

Fixes #2901
Should close #2831

Should fix #2688
Should fix #2609
Both of these relate to WebKit - while it doesn't support DASH, the HLS transcodes work for me.

Could fix #2934 - I tried one HEVC video and the resolution was correct.

### CODE REVIEW

**Comment by bnkai** [comment]
As mentioned in #3020 i can also confirm more cpu usage both on server (running stash) and on client (using firefox in a debian linux distro) for the dash vp9 part . It seems that there is a measureable extra overhead from the file concatenation and chunk encoding in the server part and an extra overhead to the browser (at least for firefox, due to the extra js library for the dash support?). For reference i tried a few 1080p 29.970 fps (so that the fps are close to the now  used 30 ) wmv files with and without forcing a 720p resize (via max live transcode option). The dash webm ends up  with not as a smooth playback as the `original` plain webm version

Was there a reason to use dash with vp9 instead of dash and h264 (x264 with the veryfast preset is way faster and less resource heavy)? The extra overhead from the filesystem could be compensated by the lower cpu usage for the x264 encoding? HLS with mp4 seems to work fine

Also do we need to completely remove the non dash webm implementation? VP9/WEBM is a nice combination since it is streaming compatible and  supported by many browsers natively (unlike dash with webm) with the only issue being that VP9 is `slow` when encoding even with the realtime option.

**Comment by DingDongSoLong4** [comment]
The reason (at least how I see it) for this whole DASH/HLS overhaul is to no longer need to use the hacky `live.ts` videojs plugin which more or less emulates scrubbing for the live transcodes as they are essentially livestreams. DASH is just needed to keep VP9 encoding as an option because HLS only supports H264 - HLS is much more widely supported, even natively in Safari and mobile browsers, in comparison to DASH which has more overhead and is completely unsupported in Safari.
If we ditch VP9 transcoding entirely then there would be no need to use DASH at all, but for those who have the hardware that can handle VP9 it should theoretically offer better quality.

I've just done a quick test on the difference in encoding time for a 5 minute wmv file and a 5 minute mp4 (both 23.976fps), and it seems to take around 10% longer on my PC (wmv 160s vs 174s, mp4 101s vs 114s). With a native 30fps mp4 file however both give identical results of 129s, so I think the overhead here is coming from the framerate conversion and not the splitting/filesystem. I'll look into avoiding that forced 30fps.

**Comment by DingDongSoLong4** [comment]
All the 30fps limits are now gone, and the encoding time after a quick test is now virtually identical to `develop`.
I also think I've figured out why the player was stuttering at the beginning of the video so I'll get to fixing that.

**Comment by WithoutPants** [comment]
In the latest version I'm not seeing any of the stuttering at the start of the video. However, the dash implementation doesn't appear to have seamless segment splitting. As the file is playing it, there's definite gaps in the playback where it's skipping forward in the playback. I've also had issues where the video errors out or hangs. So far, I haven't seen any problems with HLS playback.

**Comment by DingDongSoLong4** [comment]
I've changed things up a bit, so segments are now queued for transcode. Playback should be more reliable now.

I see what skipping you're talking about, and it seems like that is happening because when the ffmpeg process is terminated (even gracefully with an interrupt) it doesn't finish writing the current segment and leaves a partial segment behind. The partial segment then means a bit of the video is missing which causes the player to skip. For HLS this isn't a problem because it writes to a temp file first which is then renamed, but the webm_chunk muxer doesn't have this option.
The only real way I can think of which would fix this would be to have stash do the temp file renaming itself, which would probably involve directory watching and be rather complicated. Embedding the ffmpeg libraries and calling them directly would also allow for a fix, and would likely improve performance and be easier to work with later on, but would be very big and difficult to add so I don't know if that's a good idea or not. I'll probably end up trying to get the former working, but that might take a while.

**Comment by WithoutPants** [comment]
Given that DASH isn't currently working smoothly. I think this should be split further, and we should not remove the `live` plugin just yet. 

For the moment, I think we should split out the HLS overhaul and give that a thorough test. We can consider a second PR to preference HLS by default over the legacy live transcoding - and probably provide a setting to change the default behaviour.

DASH can be considered separately _if_ it is necessary to replace the current VP9 implementation.

**Comment by DingDongSoLong4** [comment]
Split into #3274 and #3275.

**Pull request closed without merging**
