### PR TITLE
Add scene queue keyboard shortcuts

### LINKED ISSUE #1423: [Feature] Keyboard shortcut for next scene in scene view
**Describe the solution you'd like**
While I'm in a scene's detail view, (with the video playing on the right side and details on the left) editing a scene I would like a shortcut for the next/previous scene. It would make going through scenes so much more convenient for tagging/marker purposes. It's a bit of a pain needing to back out then click in to the next scene.  I'm sure there's other use cases for such a feature as well. Cheers!

### PR DESCRIPTION
**Pull request by WithoutPants**
Resolves #1423 

Adds shortcut to queue tab (`q`), play next scene in queue (`p n`), previous scene (`p p`), and play random scene in queue (`p r`).

### CODE REVIEW

**Comment by kermieisinthehouse** [comment]
These shortcuts seem a little difficult. What about WASD/HJKL/Arrow keys?

**Comment by WithoutPants** [comment]
Arrow keys are used by the video player. `a` is used to show the scene details tab. `d d` is used to delete a scene if edit tab is shown. `s s` is used to save the scene. `k` is used to show the markers tab. `p r` is used already to navigate to a random item from the query page, so it makes sense to maintain the same shortcut for that. `n` and `p` would be ideal since VLC uses the same shortcuts, but `n` collides with the new marker shortcut if the markers page is shown, and `p` would mean that the `p r` shortcut would not work. 

Of the remaining options, `w` doesn't strike me as intuitive, nor does `h`, `j` or `l`. Other options I'd consider would be `,` and `.` (`<`, `>` for previous and next). The `p` prefix makes sense to me because the play random shortcut uses it.

**Comment by gitgiggety** [comment]
Tested in Firefox and Chrome and works as described. But I have to agree that it isn't very intuitive, although "Play Next", "Play Previous" and "Play Random" are quite easy to remember for `p n`, `p p` and `p r`.

Just to add, MPV uses `<` and `>` by default (so shift is required), but obviously that doesn't give a real option for random. Other options might be `9` `0` for `(` `)` without shift, or `[` `]` / `{` `}`

But I have to agree that VLCs `n` and `p` would be ideal, but if it requires "remapping" others it would obviously be a backwards compatibility breakage which should be carefully thought through. (My personal guess without any knowledge/info: I would think that `n` for new marker isn't used that much, and `n` for next in playlist might be way more popular. So maybe remapping it (and `p r` for random on the overview) _might_ be an option as it's easier to use / remember for a lot of users while possibly only a small group have to "re-calibrate" that "new marker" has a new shortcut)

**Comment by kermieisinthehouse** [comment]
I agree, breaking backward compatibility for old shortcuts to make a more consistent mapping now would be best. 

Since left / right is already mapped to jwplayer, perhaps up and down could be used to change scenes? Betterfap (now defunct) had an excellent keyboard mapping which even included gamepad support. WASD / arrow keys / d-pad were used for next/previous scene and "liking" or "disliking" for their recommender. Perhaps the existing "tab" navigation could go to the numpad, e.g. 1-6 for Scene, Queue, Markers, Edit tabs, etc.

**Comment by gitgiggety** [comment]
Up and down are used by jwplayer as well, to modify the volume. (On the subject of conflicting shortcuts, `f` obviously is fullscreen in jwplayer, but also opens the File Info tab).

Using numpad for the tabs would be odd I guess. This as the same tab might exists for multiple types but be in a different position (i.e. file info and edit are the last tabs, but scenes has way more tabs than image or gallery). So you then would have to remember the tab position per type or count the number of tabs. Prefixing tab shortcuts with `t` might also work, but my guess would be that that would mean a lot of users have to relearn the shortcuts. So if (lots of) shortcuts are changed then an RFC needs to be made to properly design all of them. (Other options would be combinations like `m n` for new marker, `m <X>` to view marker X in the current scene etc. More like prefixing the shortcut with the type you're performing the operation on).

**Review by bnkai — APPROVED** [review]

**Comment by bnkai** [comment]
Imho the keyboard shortcuts selected are fine considering the existing ones. If needed i think it is better to create a new RFC issue to discuss the remapping of the shortcuts as a whole (as mentioned above).

**Comment by WithoutPants** [comment]
Good discussion points, but yeah might be better to discuss in a separate RFC issue. I'll merge this so that at least the functionality is in there.

**Pull request merged**
