### PR TITLE
Fix Performer Studio filtering

### LINKED ISSUE #1482: [Bug Report] Performer Studio Includes Filter is broken
**Describe the bug**
In Studio Performers i get `Response not successful: Received status code 422`
Also happens if i use the studio filter in Performers
**To Reproduce**
happens every time

**Screenshots**
Screenshot 2021-06-05 at 10-46-31 Stash
Screenshot 2021-06-05 at 10-38-45 Stash

**Stash Version: (from Settings -> About):**
v0.7.0-47-g732cc571

**Additional context**
I think https://github.com/stashapp/stash/pull/1397 broke it

### PR DESCRIPTION
**Pull request by WithoutPants**
Fixes #1482 

Applied the new hierarchical studio filtering for performer query. I've left the existing implementation in there for `depth = 0` since it seems more performant. I haven't spent a long time trying to improve performance. @gitgiggety if you get the chance could you take a look at the changes? I'll merge this in now so that at least the query should work correctly.

Also fixed issue with the UI studio hook that caused the wrong criterion modifier to be used.

### CODE REVIEW

**Comment by gitgiggety** [comment]
Didn't see the code for this yet and only glanced at it yesterday.
Personally I was thinking about solving this using another CTE which would union all performers for the studios, something like:
```sql
WITH RECURSIVE studios AS (....),
performer_studios AS (
    SELECT performer_id
    FROM scenes_performers
    INNER JOIN scenes ON scenes.id = scenes_performers.scene_id
    INNER JOIN studio ON scenes.studio_id = studio.id
  UNION
    SELECT performer_id
    FROM images_performers
    INNER JOIN images ON images.id = performers_scenes.image_id
    INNER JOIN studio ON images.studio_id = studio.id
  UNION
    <repeat for galleries>
)
SELECT ...
FROM performers
LEFT JOIN performer_studios ON performer_studios.performer_id = performers.id
WHERE performer_studios.performer_id IS [NOT] NULL
```

Using the `UNION` will already remove any duplicates so there won't be any additional rows added by the `JOIN`. And using a `JOIN` might be better as the current solution has to run at least one (and at most three) subquery for every performer in the database. And will thus run at least "1 * total performer count" subqueries and at most "3 * total performer count" subqueries. While with this `UNION` solution it will have to read the <type>_performers table only once.

But checking the current query once more I guess it could also be optimised by removing the `COUNT(DISTINCT id)`. We're not interested in the count anyway, we only want to know it there is a match (or not). In other words I believe this could be changed to the following as well:
```sql
WHERE [NOT] (
  EXISTS(SELECT 1 FROM <performers by scene WHERE performer_id and studio_id match>) OR
  EXISTS(SELECT 1 FROM <performers by image WHERE performer_id and studio_id match>) OR
  EXISTS(SELECT 1 FROM <performers by gallery WHERE performer_id and studio_id match>)
)
```
So replacing the `COUNT(DISTINCT id)` with a dummy value, and wrapping it in an `EXISTS` call. This as databases should be optimized to stop searching when one match is found for an `EXISTS` call and it thus doesn't have to go over all records to count all matches. As soon as there is a match it can stop searching.

I hope this is the answer you were looking for from me 😄. But at least the code comment for "optimize for depth = 0" led me into this direction.

(Note: comment written on phone so code obviously will be full of errors / incorrect names as I didn't have all the information at hand. But hopefully it will be clear what I mean)

**Comment by gitgiggety** [comment]
So I had some time at computer (but still not my development computer) and wrote the following query, which should equal something generated in code (using same combination of DISTINCT, GROUP BY, ORDER BY, LIMIT etc)
```sql
WITH RECURSIVE studio AS (
  SELECT id as id, id as child_id, 0 as depth FROM studios
  WHERE id in (54)
  UNION SELECT p.id, c.id, depth + 1 FROM studios as c
  INNER JOIN studio as p ON c.parent_id = p.child_id
),
performer_studio AS (
    SELECT performer_id
    FROM performers_scenes
    INNER JOIN scenes ON performers_scenes.scene_id = scenes.id
    INNER JOIN studio ON studio.child_id = scenes.studio_id
  UNION
    SELECT performer_id
    FROM performers_images
    INNER JOIN images ON performers_images.image_id = images.id
    INNER JOIN studio ON studio.child_id = images.studio_id
  UNION
    SELECT performer_id
    FROM performers_galleries
    INNER JOIN galleries ON performers_galleries.gallery_id = galleries.id
    INNER JOIN studio ON studio.child_id = galleries.studio_id
)
SELECT DISTINCT id
FROM performers
LEFT JOIN performer_studio ON performers.id = performer_studio.performer_id
WHERE performer_studio.performer_id IS NOT NULL
GROUP BY performers.id
ORDER BY performers.name COLLATE NOCASE ASC
LIMIT 40;
```

But for me both queries are executed instantly (because of a small DB I guess, although still having 170 performers), so I can't really tell if this works better or not. I've tested this by putting both queries in a file and then executing `time sqlite3 [path to DB file] < [path to SQL file]` and both take 0.00s or 0.01.

But the query plans are very different:
This is the query plan for the query posted above:
```
QUERY PLAN
|--MATERIALIZE 5
|  `--COMPOUND QUERY
|     |--LEFT-MOST SUBQUERY
|     |  |--MATERIALIZE 2
|     |  |  |--SETUP
|     |  |  |  `--SEARCH TABLE studios USING INTEGER PRIMARY KEY (rowid=?)
|     |  |  `--RECURSIVE STEP
|     |  |     |--SCAN TABLE studio AS p
|     |  |     `--SEARCH TABLE studios AS c USING AUTOMATIC COVERING INDEX (parent_id=?)
|     |  |--SCAN TABLE performers_scenes
|     |  |--SEARCH TABLE scenes USING INTEGER PRIMARY KEY (rowid=?)
|     |  `--SEARCH SUBQUERY 2 USING AUTOMATIC COVERING INDEX (child_id=?)
|     |--UNION USING TEMP B-TREE
|     |  |--MATERIALIZE 2
|     |  |  |--SETUP
|     |  |  |  `--SEARCH TABLE studios USING INTEGER PRIMARY KEY (rowid=?)
|     |  |  `--RECURSIVE STEP
|     |  |     |--SCAN TABLE studio AS p
|     |  |     `--SEARCH TABLE studios AS c USING AUTOMATIC COVERING INDEX (parent_id=?)
|     |  |--SCAN TABLE performers_images
|     |  |--SEARCH TABLE images USING INTEGER PRIMARY KEY (rowid=?)
|     |  `--SEARCH SUBQUERY 2 USING AUTOMATIC COVERING INDEX (child_id=?)
|     `--UNION USING TEMP B-TREE
|        |--MATERIALIZE 2
|        |  |--SETUP
|        |  |  `--SEARCH TABLE studios USING INTEGER PRIMARY KEY (rowid=?)
|        |  `--RECURSIVE STEP
|        |     |--SCAN TABLE studio AS p
|        |     `--SEARCH TABLE studios AS c USING AUTOMATIC COVERING INDEX (parent_id=?)
|        |--SCAN TABLE performers_galleries
|        |--SEARCH TABLE galleries USING INTEGER PRIMARY KEY (rowid=?)
|        `--SEARCH SUBQUERY 2 USING AUTOMATIC COVERING INDEX (child_id=?)
|--SCAN TABLE performers
|--SEARCH SUBQUERY 5 USING AUTOMATIC COVERING INDEX (performer_id=?)
|--USE TEMP B-TREE FOR DISTINCT
`--USE TEMP B-TREE FOR ORDER BY
```

And this is the (formatted) query as generated on the develop branch:
```sql
WITH RECURSIVE studio AS (
  SELECT id as id, id as child_id, 0 as depth FROM studios 
  WHERE id in (54) 
  UNION SELECT p.id, c.id, depth + 1 FROM studios as c 
  INNER JOIN studio as p ON c.parent_id = p.child_id
)
SELECT DISTINCT performers.id
FROM performers
WHERE
  (
    (
      SELECT COUNT(DISTINCT scenes.id)
      FROM scenes
      LEFT JOIN performers_scenes ON scenes.id = performers_scenes.scene_id 
      INNER JOIN studio ON scenes.studio_id = studio.child_id
      WHERE performers_scenes.performer_id = performers.id
    ) > 0
    OR
    (
      SELECT COUNT(DISTINCT images.id)
      FROM images
      LEFT JOIN performers_images ON images.id = performers_images.image_id 
      INNER JOIN studio ON images.studio_id = studio.child_id
      WHERE performers_images.performer_id = performers.id
    ) > 0
    OR
    (
      SELECT COUNT(DISTINCT galleries.id)
      FROM galleries
      LEFT JOIN performers_galleries ON galleries.id = performers_galleries.gallery_id 
      INNER JOIN studio ON galleries.studio_id = studio.child_id
      WHERE performers_galleries.performer_id = performers.id
    ) > 0
  )
GROUP BY performers.id
ORDER BY performers.name COLLATE NOCASE ASC
LIMIT 40

```
which results in the following query plan:
```
QUERY PLAN
|--SCAN TABLE performers
|--CORRELATED SCALAR SUBQUERY 3
|  |--MATERIALIZE 2
|  |  |--SETUP
|  |  |  `--SEARCH TABLE studios USING INTEGER PRIMARY KEY (rowid=?)
|  |  `--RECURSIVE STEP
|  |     |--SCAN TABLE studio AS p
|  |     `--SEARCH TABLE studios AS c USING AUTOMATIC COVERING INDEX (parent_id=?)
|  |--SEARCH TABLE performers_scenes USING INDEX index_performers_scenes_on_performer_id (performer_id=?)
|  |--SEARCH TABLE scenes USING INTEGER PRIMARY KEY (rowid=?)
|  `--SEARCH SUBQUERY 2 USING AUTOMATIC COVERING INDEX (child_id=?)
|--CORRELATED SCALAR SUBQUERY 4
|  |--MATERIALIZE 2
|  |  |--SETUP
|  |  |  `--SEARCH TABLE studios USING INTEGER PRIMARY KEY (rowid=?)
|  |  `--RECURSIVE STEP
|  |     |--SCAN TABLE studio AS p
|  |     `--SEARCH TABLE studios AS c USING AUTOMATIC COVERING INDEX (parent_id=?)
|  |--SEARCH TABLE performers_images USING INDEX index_performers_images_on_performer_id (performer_id=?)
|  |--SEARCH TABLE images USING INTEGER PRIMARY KEY (rowid=?)
|  `--SEARCH SUBQUERY 2 USING AUTOMATIC COVERING INDEX (child_id=?)
|--CORRELATED SCALAR SUBQUERY 5
|  |--MATERIALIZE 2
|  |  |--SETUP
|  |  |  `--SEARCH TABLE studios USING INTEGER PRIMARY KEY (rowid=?)
|  |  `--RECURSIVE STEP
|  |     |--SCAN TABLE studio AS p
|  |     `--SEARCH TABLE studios AS c USING AUTOMATIC COVERING INDEX (parent_id=?)
|  |--SEARCH TABLE performers_galleries USING INDEX index_performers_galleries_on_performer_id (performer_id=?)
|  |--SEARCH TABLE galleries USING INTEGER PRIMARY KEY (rowid=?)
|  `--SEARCH SUBQUERY 2 USING AUTOMATIC COVERING INDEX (child_id=?)
|--USE TEMP B-TREE FOR DISTINCT
`--USE TEMP B-TREE FOR ORDER BY
```

Using the original query, but `EXISTS()` instead of `(SELECT COUNT ...) > 0` would result in this query:
```sql
WITH RECURSIVE studio AS (
  SELECT id as id, id as child_id, 0 as depth FROM studios 
  WHERE id in (54) 
  UNION SELECT p.id, c.id, depth + 1 FROM studios as c 
  INNER JOIN studio as p ON c.parent_id = p.child_id
)
SELECT DISTINCT performers.id
FROM performers
WHERE
  (
    EXISTS(
      SELECT 1
      FROM scenes
      LEFT JOIN performers_scenes ON scenes.id = performers_scenes.scene_id 
      INNER JOIN studio ON scenes.studio_id = studio.child_id
      WHERE performers_scenes.performer_id = performers.id
    )
    OR
    EXISTS(
      SELECT 1
      FROM images
      LEFT JOIN performers_images ON images.id = performers_images.image_id 
      INNER JOIN studio ON images.studio_id = studio.child_id
      WHERE performers_images.performer_id = performers.id
    )
    OR
    EXISTS(
      SELECT 1
      FROM galleries
      LEFT JOIN performers_galleries ON galleries.id = performers_galleries.gallery_id 
      INNER JOIN studio ON galleries.studio_id = studio.child_id
      WHERE performers_galleries.performer_id = performers.id
    )
  )
GROUP BY performers.id
ORDER BY performers.name COLLATE NOCASE ASC
LIMIT 40

```
which results in an identical query plan, so SQLite might actually optimize that already.

My personal opinion would be to switch to my first approach, so using the additional CTE, as it looks a bit cleaner IMO. But if the `EXISTS()` solution results in a better performance that would be fine to. The current query, using `COUNT` is most likely harder to read, while not giving any benefit (as `EXISTS` should be better anyway, and is easier to read / understand, and as the query plan is identical it shouldn't be slower anyway).

So if my feedback was desired on the performance case you can try both of these queries. If needed I can then obviously implement either of them, or you can most likely make the necessary changes as well yourself.

**Comment by WithoutPants** [comment]
Thank you. This is very comprehensive and helpful.

**Comment by gitgiggety** [comment]
So do you want me so implement either of these queries? I at least can use my development PC again so I can make the changes. But as stated before, I'm not seeing any performance issues / differencea with either of the three queries, so if one query is faster than another you'll have to tell me which to use. And the same applies to the `depth == 0` optimization, it might be that that isn't necessary anymore either then?

And for `depth == 0` the recursive base query might also be optimised to a fixed list like such:
```sql
WITH studio(id, child_id, depth) AS (
  VALUES
  (<filter value 1>, <filter value 1>, 0),
  (<filter value 2>, <filter value 2>, 0),
  [...]
)
```
Which would mean SQLite shouldn't even need to look up the ids in the table. (Obviously this could be used as starting point of the recursive query as well).

**Comment by gitgiggety** [comment]
@WithoutPants any update on this? Do you want me to make some changes for this? / Did you get the change to test both queries (obviously can be run using the `sqlite3` client after inserting some studio id(s)) to check if one of them has a considerably better performance after which I can implement one of them.

**Comment by WithoutPants** [comment]
Sorry for not getting back sooner. I've quickly tested these queries against a large contrived database - the caveat is that the database doesn't have any parent/child studio relationships, so it's not an exhaustive test.

In any case, your proposed query was significantly faster than the others:

Proposed query: 0.5s
Dev branch version: 3.5s
Dev branch with `EXISTS`: 0.5s

So I definitely think your change is worth implementing. If you're happy to make the change, I think it's worth including in 0.8.

**Comment by gitgiggety** [comment]
Whoa, that's a massive difference indeed. Guess you're also testing using a massive (generated) DB then.

As the performance of both proposed queries is about the same... And I forgot to test / provide queries for the "excludes" (which might differ as well) could you test these as well?
**Using WITH** (`IS NOT NULL` => `IS NULL`):
```sql
WITH RECURSIVE studio AS (
  SELECT id as id, id as child_id, 0 as depth FROM studios
  WHERE id in (54)
  UNION SELECT p.id, c.id, depth + 1 FROM studios as c
  INNER JOIN studio as p ON c.parent_id = p.child_id
),
performer_studio AS (
    SELECT performer_id
    FROM performers_scenes
    INNER JOIN scenes ON performers_scenes.scene_id = scenes.id
    INNER JOIN studio ON studio.child_id = scenes.studio_id
  UNION
    SELECT performer_id
    FROM performers_images
    INNER JOIN images ON performers_images.image_id = images.id
    INNER JOIN studio ON studio.child_id = images.studio_id
  UNION
    SELECT performer_id
    FROM performers_galleries
    INNER JOIN galleries ON performers_galleries.gallery_id = galleries.id
    INNER JOIN studio ON studio.child_id = galleries.studio_id
)
SELECT DISTINCT id
FROM performers
LEFT JOIN performer_studio ON performers.id = performer_studio.performer_id
WHERE performer_studio.performer_id IS NULL
GROUP BY performers.id
ORDER BY performers.name COLLATE NOCASE ASC
LIMIT 40;
```

**Original** (modified based on code, so `> 0` => `= 0` and `OR` => `AND`, didn't check actual generated query):
```sql
WITH RECURSIVE studio AS (
  SELECT id as id, id as child_id, 0 as depth FROM studios 
  WHERE id in (54) 
  UNION SELECT p.id, c.id, depth + 1 FROM studios as c 
  INNER JOIN studio as p ON c.parent_id = p.child_id
)
SELECT DISTINCT performers.id
FROM performers
WHERE
  (
    (
      SELECT COUNT(DISTINCT scenes.id)
      FROM scenes
      LEFT JOIN performers_scenes ON scenes.id = performers_scenes.scene_id 
      INNER JOIN studio ON scenes.studio_id = studio.child_id
      WHERE performers_scenes.performer_id = performers.id
    ) = 0
    AND
    (
      SELECT COUNT(DISTINCT images.id)
      FROM images
      LEFT JOIN performers_images ON images.id = performers_images.image_id 
      INNER JOIN studio ON images.studio_id = studio.child_id
      WHERE performers_images.performer_id = performers.id
    ) = 0
    AND
    (
      SELECT COUNT(DISTINCT galleries.id)
      FROM galleries
      LEFT JOIN performers_galleries ON galleries.id = performers_galleries.gallery_id 
      INNER JOIN studio ON galleries.studio_id = studio.child_id
      WHERE performers_galleries.performer_id = performers.id
    ) = 0
  )
GROUP BY performers.id
ORDER BY performers.name COLLATE NOCASE ASC
LIMIT 40;
```

**Exists** (just added a `NOT` before the `(... OR ... OR ...)` which should be the same as `(NOT EXISTS(...) AND NOT EXISTS(...) AND NOT EXISTS(...))`):
```sql
WITH RECURSIVE studio AS (
  SELECT id as id, id as child_id, 0 as depth FROM studios 
  WHERE id in (54) 
  UNION SELECT p.id, c.id, depth + 1 FROM studios as c 
  INNER JOIN studio as p ON c.parent_id = p.child_id
)
SELECT DISTINCT performers.id
FROM performers
WHERE
  NOT (
    EXISTS(
      SELECT 1
      FROM scenes
      LEFT JOIN performers_scenes ON scenes.id = performers_scenes.scene_id 
      INNER JOIN studio ON scenes.studio_id = studio.child_id
      WHERE performers_scenes.performer_id = performers.id
    )
    OR
    EXISTS(
      SELECT 1
      FROM images
      LEFT JOIN performers_images ON images.id = performers_images.image_id 
      INNER JOIN studio ON images.studio_id = studio.child_id
      WHERE performers_images.performer_id = performers.id
    )
    OR
    EXISTS(
      SELECT 1
      FROM galleries
      LEFT JOIN performers_galleries ON galleries.id = performers_galleries.gallery_id 
      INNER JOIN studio ON galleries.studio_id = studio.child_id
      WHERE performers_galleries.performer_id = performers.id
    )
  )
GROUP BY performers.id
ORDER BY performers.name COLLATE NOCASE ASC
LIMIT 40;
```

I will then try to make the necessary changes over the weekend.

**Comment by WithoutPants** [comment]
These results are with another generated database. The main difference is that the new database includes studio hierarchies.

Using with: 0.081s
Original code: 2.601s
Exists: 2.528s

I retested the earlier queries as well, here's the results for comparison:
Proposed query: 0.074s
Original code: 2.567
Exists: 2.522s

**Comment by gitgiggety** [comment]
Thank you. I guess the 0.5s for the exists query was an error/typo then and should have been 3.5s as well? Because it's the same as the original now. And I can't really explain the difference otherwise (why exists would be a lot quicker when there is no studio hierarchy). And as I wrote before I can imagine that databases are smart enough to optimize a `(SELECT COUNT(...) FROM ...) > 0` into either an exists or just optimize it all together and just stop counting when the threshold is met (so not only optimizing `> 0` or `>= 1` but every `> X` by just adding a kinda LIMIT on the subquery)

BTW: just saw your PR for the test database generator as well. I will have a go with it and might try to do some more SQL optimizations over time.

**Pull request merged**
