### PR TITLE
Add shortcuts for decimal rating

### LINKED ISSUE #3225: [Feature] Update Rating Shortcuts for Decimals
**Is your feature request related to a problem? Please describe.**
After the update of the rating system, keyboard shortcuts doesn't reflect the behaviour for the decimal system

**Describe the solution you'd like**
Make that, i.e., `r 9` puts a 9,0 rate

### PR DESCRIPTION
**Pull request by apache202119**
Resolves #3225

Not sure what key to use for resetting the rating, as I set `0` for 10.0 already

### CODE REVIEW

**Comment by skier233** [comment]
> 

Perhaps you could use ` to reset the rating since it is on the left of 1.

**Comment by apache202119** [comment]
> > 
> 
> Perhaps you could use ` to reset the rating since it is on the left of 1.

That was my first thought but that key it's not on the left for international keyboards.

**Comment by skier233** [comment]
> > > 
> > 
> > 
> > Perhaps you could use ` to reset the rating since it is on the left of 1.
> 
> That was my first thought but that key it's not on the left for international keyboards.

I don't think it's possible to have a key thats in the same spot for everyone. Just have to make a compromise.

**Comment by apache202119** [comment]
> > > > 
> > > 
> > > 
> > > Perhaps you could use ` to reset the rating since it is on the left of 1.
> > 
> > 
> > That was my first thought but that key it's not on the left for international keyboards.
> 
> I don't think it's possible to have a key thats in the same spot for everyone. Just have to make a compromise.

Done

**Comment by WithoutPants** [comment]
I made some changes to this branch. For decimal ratings, I believe accepting two key presses would be better - ie `r 8 5` sets rating to `8.5`. I generalised the repeated rating keybind code into a separate hook and applied this to the other pages. I also updated the manual page accordingly.

**Comment by erebous** [comment]
Sometimes I need to press the key combination (e.g. r 1 0) a couple of times for this to work

**Pull request merged**
