### PR TITLE
Add descriptions to tags and display tag cards on hover

### LINKED ISSUE #1444: [Feature] Add Descriptions to Tags
**Is your feature request related to a problem? Please describe.**
Tags aren’t currently able to have a description set. Even (or especially) with tag aliases now enabled, it becomes important to be able to define what a tag means.

**Describe the solution you'd like**
Tags are updated to include a description property, and thus a description field in the UI. In addition, including a preview of the description in the tags dropdown would be amazing (but can be skipped if it’s too much work)

**Describe alternatives you've considered**
None

**Additional context**
The reason I mention tag aliases is that it highlights the need for a description. For example let’s say I have a tag called `skinny` and it has an alias `petite`. That makes sense, but I might also have a tag `tiny` that seems like it would fit under `skinny`, but in my categorization it means something different. In this case `tiny` is looking at the overall package, someone who’s both short and skinny, and is more of a gut feeling kind of tag. It’s hard to know that offhand, and when tagging if there are a few sets of tags that are like that then it can be hard to keep it straight. Having those descriptions helps with that, and keeps the tagging methodology consistent.

### LINKED ISSUE #2575: [Feature] Display Tag Description & Tag Image on hover
This is a UI focused feature request that elaborates further on https://github.com/stashapp/stash/issues/1444 (Add descriptions to tags)

Today, the images that can be added to tags are underutilized-- we currently only display them on the Tags page. 
With the request for Tag Descriptions already out as an open feature request, imo this is a great time to consider a new UI element here that would tie everything together.

I propose we display the description of the tag _as well as_ the associated tag image when hovering over an added tag tag (on the Details or Edit tab) or when hovering over a tag name in the tag dropdown form.

Below are some UI examples of what I'm thinking of...

**- Edit Tab, Tag Dropdown form** 
StashIdeaForTagHover2

**- Edit Tab, On hover of an added Tag**
StashIdeaForTagHover

**- Details Tab, On hover of an added Tag**
StashIdeaForTagHover3

Thanks! 🙂

### PR DESCRIPTION
**Pull request by pickleahead**
Closes #1444 
Closes #2575

- Tags get a description field
- Tag cards are shown when hovering tag badges and tag select options
- Adds an option to the interface basic settings section to enable this feature

### CODE REVIEW

**Comment by WithoutPants** [comment]
#2676 is going to be the next large PR to be merged and this will need to be rebased after that PR is merged.

**Review by WithoutPants — APPROVED** [review]

**Comment by WithoutPants** [comment]
@pickleahead you are eligible for the bounties for #2575 and #1444. Please submit an expense to the OpenCollective for $86.02 ($100 - OpenCC fees) and mention the invoice number here, or otherwise indicate what you want done with the bounty.

**Comment by pickleahead** [comment]
@WithoutPants Would it be possible to place the bounty on another issue?

**Comment by WithoutPants** [comment]
> @WithoutPants Would it be possible to place the bounty on another issue?

Yes, absolutely. Mention me in the applicable issue, and I'll sort it out.

**Pull request merged**
