### PR TITLE
Mobile scene details page revamp

### PR DESCRIPTION
**Pull request by Teda1**
This pull request improves the user experience on the scene details page. The video and nav tabs will now stay in view as you scroll through scene details, markers, filters, etc. See https://discord.com/channels/559159668438728723/644934273459290145/959594477079629965 for Demo.

### CODE REVIEW

**Comment by WithoutPants** [comment]
The o-counter, organized and overflow menu buttons are no longer visible.

image
(old)
image

**Comment by Teda1** [comment]
Ideally, I'd like to bring that section out of the tablist and into one of the tabs. But if I was going to make this change with just CSS I think the best option would be to float those items down to the navbar.

Screenshot 2022-04-02 093846

**Comment by Teda1** [comment]
How about this:
Screenshot 2022-04-02 145234
Screenshot 2022-04-02 145219

**Comment by WithoutPants** [comment]
You've still lost the organized flag. Can you not put the controls on the next row? We can always hide it in custom css.

**Comment by Teda1** [comment]
I'll give that a go.

**Comment by Teda1** [comment]
This isn't too bad.
Screenshot 2022-04-02 151609
Screenshot 2022-04-02 151710
Screenshot 2022-04-02 151627

**Comment by WithoutPants** [comment]
I think it would look better right-justified.

**Comment by Teda1** [comment]
Yeah, I fixed that after posting. I'll push something up soon.

**Comment by Teda1** [comment]
Results after the change I just pushed.
Screenshot 2022-04-02 163013

**Comment by WithoutPants** [comment]
The overflow menu appears under the edit buttons:

image

**Comment by Teda1** [comment]
That problem should be gone now.
Screenshot 2022-04-02 232038

**Review by WithoutPants — APPROVED** [review]

**Pull request merged**
