### PR TITLE
Saved filters

### LINKED ISSUE #99: [Feature] Allow user to set default scene page parameters in settings
Whenever I go to my scene page I always have to set my _sortby_ to _created_at_, _sortdir_ to _desc_, and other sorting, filter, and display parameters exactly how I want them.

Consider having a section in the settings page that lets the user define the default parameters for the scene page.

### LINKED ISSUE #730: [Feature] Saved queries
**Is your feature request related to a problem? Please describe.**
It should be possible to save frequently used queries.

**Describe the solution you'd like**
Having set query parameters for a given page, it should be possible to save the query parameters. These saved queries should then be easily accessible from a dropdown menu or something. It should be possible to set a saved query as a default query for a list page, such that if no existing query is in memory, it will use the saved query as the default.

**Describe alternatives you've considered**
It is possible to use bookmarks to save queries, but this is not a very discreet solution.

### PR DESCRIPTION
**Pull request by WithoutPants**
Includes a further refactoring of the UI filter system. I can separate out the saved filter stuff from the refactoring if necessary.

Adds a "Saved Filters" button to the search text field. Clicking the button shows a dropdown list of saved filters:

image

Typing into the "Filter name" field filters the saved filters displayed. Provided that the entered name is unique, the save button is enabled next to it, allowing the current filter to be saved. Existing filters can also be overwritten or deleted. Clicking on an existing filter applies it.

The Set Default button sets the default filter and view for the page. This is enabled only in the top-level pages (ie where `persistState` is `ALL`). When navigating to the top-level page, if no URL parameters are present (ie from clicking to top navbar buttons), then the default filter is applied. This supercedes the behaviour introduced by #326 that maintained the filter across all visits to the query page. Now, only the display mode is persisted in cookies for components using `persistState` of `VIEW`.

Resolves #99
Resolves #730 
Overlap with #1434

### CODE REVIEW

**Comment by yoshnopa** [comment]
I hope this is the right place to propose this, otherwise this could be made an issue.
I think a saved filter is great, but it would be more useful if the sorting and maybe even the view type (grid/list) would be saved that way as well.
depending on the filter and the amount of results, other views or sortings may be necessary. That way, this could be preserved. On the other hand, those barely using views and/or sorting changes won't even notice this enhancement, so no drawback for other use cases.

**Comment by WithoutPants** [comment]
> I hope this is the right place to propose this, otherwise this could be made an issue.
> I think a saved filter is great, but it would be more useful if the sorting and maybe even the view type (grid/list) would be saved that way as well.
> depending on the filter and the amount of results, other views or sortings may be necessary. That way, this could be preserved. On the other hand, those barely using views and/or sorting changes won't even notice this enhancement, so no drawback for other use cases.

Sorting and view type is saved in the saved filter.

**Comment by kermieisinthehouse** [comment]
It seems to reflow strangely on mobile with the new button on the scenes page

**Comment by WithoutPants** [comment]
Made some adjustments to the styling. I'm not super happy with the presentation of the filter UI in general, but I'll save that for another PR.

**Review by bnkai — APPROVED** [review]

**Pull request merged**
