### PR TITLE
Replace packr with go embed

### PR DESCRIPTION
**Pull request by WithoutPants**
Based on https://github.com/stashapp/stash-box/pull/118

Replaces packr with go:embed directives.

### CODE REVIEW

**Review by kermieisinthehouse — CHANGES_REQUESTED** [review]
This is a great cleanup! Losing dependencies is a major win!

There are still calls to packr in a few places:
- The makefile contains `make packr` and a few references.
- The readme still lists packr as a dependency.
- The docker images still install packr, which can be skipped.
- The GitHub actions workflow runs packr during compile.

But otherwise looks good!

**Comment by gitgiggety** [comment]
Removed packr stuff with `rm -r packrd pkg/api/api-packr.go pkg/database/database-packr.go` and ran `go run .` afterwards. Everything seems to work fine so far. Also tested creating new performers (for the randomly selected images) and used an old database (to run migrations for) and those seem to work fine too.

So it works. But @kermieisinthehouse comments obviously check out and should be fixed.

**Comment by bnkai** [comment]
I did a quick check using `grep -r "packr" .`
The below diff removes almost all entries ( A couple of lines are left in the go.sum file. I tried the `go.sum` file and recreating it, even tried a `go mod tidy` but there are still a couple of `packr` checksums in there,it shouldnt matter though )

Disclaimer: I haven't actually test the docker images/cross compile script yet the stash binary seems to work ok though 
```diff
diff --git a/.dockerignore b/.dockerignore
index 990c8acd..954624f3 100644
--- a/.dockerignore
+++ b/.dockerignore
@@ -15,16 +15,10 @@
 # Output of the go coverage tool, specifically when used with LiteIDE
 *.out
 
-# Packr2 artifacts
-**/*-packr.go
-
 # GraphQL generated output
 pkg/models/generated_*.go
 ui/v2.5/src/core/generated-*.tsx
 
-# packr generated files
-*-packr.go
-
 ####
 # Jetbrains
 ####
@@ -60,4 +54,4 @@ ui/v2.5/build
 stash
 dist
 
-docker
\ No newline at end of file
+docker
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index eed579b0..bb0ab56e 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -81,7 +81,6 @@ jobs:
 
     - name: Compile for all supported platforms
       run: |
-        docker exec -t build /bin/bash -c "make packr"
         docker exec -t build /bin/bash -c "make cross-compile-windows"
         docker exec -t build /bin/bash -c "make cross-compile-osx-intel"
         docker exec -t build /bin/bash -c "make cross-compile-osx-applesilicon"
diff --git a/.gitignore b/.gitignore
index d6c2eea2..8ea22a10 100644
--- a/.gitignore
+++ b/.gitignore
@@ -15,16 +15,10 @@
 # Output of the go coverage tool, specifically when used with LiteIDE
 *.out
 
-# Packr2 artifacts
-**/*-packr.go
-
 # GraphQL generated output
 pkg/models/generated_*.go
 ui/v2.5/src/core/generated-*.tsx
 
-# packr generated files
-*-packr.go
-
 ####
 # Jetbrains
 ####
diff --git a/Makefile b/Makefile
index c530747b..de4ec123 100644
--- a/Makefile
+++ b/Makefile
@@ -113,12 +113,6 @@ cross-compile-all:
 	make cross-compile-linux-arm32v7 
 	make cross-compile-pi
 
-install:
-	packr2 install
-
-clean:
-	packr2 clean
-
 # Regenerates GraphQL files
 generate: generate-backend generate-frontend
 
@@ -175,17 +169,13 @@ generate-test-mocks:
 pre-ui:
 	cd ui/v2.5 && yarn install --frozen-lockfile
 
-.PHONY: ui-only
-ui-only: pre-build
+.PHONY: ui
+ui: pre-build
 	$(SET) REACT_APP_DATE="$(BUILD_DATE)" $(SEPARATOR) \
 	$(SET) REACT_APP_GITHASH=$(GITHASH) $(SEPARATOR) \
 	$(SET) REACT_APP_STASH_VERSION=$(STASH_VERSION) $(SEPARATOR) \
 	cd ui/v2.5 && yarn build
 
-.PHONY: ui
-ui: ui-only
-	packr2
-
 .PHONY: ui-start
 ui-start: pre-build
 	$(SET) REACT_APP_DATE="$(BUILD_DATE)" $(SEPARATOR) \
@@ -202,13 +192,6 @@ fmt-ui:
 ui-validate:
 	cd ui/v2.5 && yarn run validate
 
-# just repacks the packr files - use when updating migrations and packed files without 
-# rebuilding the UI
-.PHONY: packr
-packr:
-	$(SET) GO111MODULE=on
-	packr2
-
 # runs all of the tests and checks required for a PR to be accepted
 .PHONY: validate
 validate: ui-validate fmt-check vet lint it
@@ -216,4 +199,4 @@ validate: ui-validate fmt-check vet lint it
 # locally builds and tags a 'stash/build' docker image
 .PHONY: docker-build
 docker-build: 
-	docker build -t stash/build -f docker/build/x86_64/Dockerfile .
\ No newline at end of file
+	docker build -t stash/build -f docker/build/x86_64/Dockerfile .
diff --git a/README.md b/README.md
index 16857797..81702616 100644
--- a/README.md
+++ b/README.md
@@ -96,9 +96,6 @@ For issues not addressed there, there are a few options.
 * [Go](https://golang.org/dl/)
 * [Revive](https://github.com/mgechev/revive) - Configurable linter
     * Go Install: `go get github.com/mgechev/revive`
-* [Packr2](https://github.com/gobuffalo/packr/) - Static asset bundler
-    * Go Install: `go get github.com/gobuffalo/packr/v2/packr2`
-    * [Binary Download](https://github.com/gobuffalo/packr/releases)
 * [Yarn](https://yarnpkg.com/en/docs/install) - Yarn package manager
     * Run `yarn install --frozen-lockfile` in the `stash/ui/v2.5` folder (before running make generate for first time).
 
@@ -127,8 +124,7 @@ NOTE: The `make` command in Windows will be `mingw32-make` with MingW.
 * `make docker-build` - Locally builds and tags a complete 'stash/build' docker image
 * `make pre-ui` - Installs the UI dependencies. Only needs to be run once before building the UI for the first time, or if the dependencies are updated
 * `make fmt-ui` - Formats the UI source code.
-* `make ui` - Builds the frontend and the packr2 files
-* `make packr` - Generate packr2 files (sub-target of `ui`. Use to regenerate packr2 files without rebuilding UI)
+* `make ui` - Builds the frontend.
 * `make vet` - Run `go vet`
 * `make lint` - Run the linter
 * `make fmt` - Run `go fmt`
diff --git a/docker/build/x86_64/Dockerfile b/docker/build/x86_64/Dockerfile
index 389a665b..2523c7a3 100644
--- a/docker/build/x86_64/Dockerfile
+++ b/docker/build/x86_64/Dockerfile
@@ -19,16 +19,8 @@ RUN BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S") make ui-only
 # Build Backend
 FROM golang:1.17-alpine as backend
 RUN apk add --no-cache xz make alpine-sdk
-## install packr, ffmpeg
-ENV PACKR2_VERSION=2.8.1
-ENV PACKR2_SHA=1cb2a0113550bc7962a8fda31a29877fcbbabd56b46c25e1fffbc225334162e7
-ENV PACKR2_DOWNLOAD_FILE=packr_${PACKR2_VERSION}_linux_amd64.tar.gz
-ENV PACKR2_DOWNLOAD_URL=https://github.com/gobuffalo/packr/releases/download/v${PACKR2_VERSION}/${PACKR2_DOWNLOAD_FILE}
+## install ffmpeg
 WORKDIR /
-RUN wget ${PACKR2_DOWNLOAD_URL}; \
-	echo "$PACKR2_SHA  $PACKR2_DOWNLOAD_FILE" | sha256sum -c - || exit 1; \
-	tar -xzf $PACKR2_DOWNLOAD_FILE -C /usr/bin/ packr2; \
-	rm $PACKR2_DOWNLOAD_FILE;
 RUN wget -O /ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz && \
     tar xf /ffmpeg.tar.xz && \
     rm ffmpeg.tar.xz && \
@@ -41,7 +33,6 @@ COPY ./vendor /stash/vendor/
 COPY ./pkg /stash/pkg/
 COPY --from=frontend /stash /stash/
 RUN make generate-backend
-RUN make packr
 RUN make build
 
 # Final Runnable Image
@@ -50,4 +41,4 @@ RUN apk add --no-cache ca-certificates
 COPY --from=backend /stash/stash /ffmpeg/ffmpeg /ffmpeg/ffprobe /usr/bin/
 ENV STASH_CONFIG_FILE=/root/.stash/config.yml
 EXPOSE 9999
-ENTRYPOINT ["stash"]
\ No newline at end of file
+ENTRYPOINT ["stash"]
diff --git a/docker/compiler/Dockerfile b/docker/compiler/Dockerfile
index 0450dabc..96fc9f16 100644
--- a/docker/compiler/Dockerfile
+++ b/docker/compiler/Dockerfile
@@ -2,11 +2,6 @@ FROM golang:1.17
 
 LABEL maintainer="https://discord.gg/2TsNFKt"
 
-ENV PACKR2_VERSION=2.8.1
-ENV PACKR2_SHA=1cb2a0113550bc7962a8fda31a29877fcbbabd56b46c25e1fffbc225334162e7
-ENV PACKR2_DOWNLOAD_FILE=packr_${PACKR2_VERSION}_linux_amd64.tar.gz
-ENV PACKR2_DOWNLOAD_URL=https://github.com/gobuffalo/packr/releases/download/v${PACKR2_VERSION}/${PACKR2_DOWNLOAD_FILE}
-
 # Install tools
 RUN apt-get update && apt-get install -y apt-transport-https
 RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
@@ -52,14 +47,6 @@ RUN mkdir -p /root/.ssh; \
     chmod 0700 /root/.ssh; \
     ssh-keyscan github.com > /root/.ssh/known_hosts;
 
-RUN  wget ${PACKR2_DOWNLOAD_URL}; \
-			echo "$PACKR2_SHA $PACKR2_DOWNLOAD_FILE" | sha256sum -c - || exit 1; \
-			tar -xzf $PACKR2_DOWNLOAD_FILE -C /usr/bin/ packr2; \
-			rm $PACKR2_DOWNLOAD_FILE;
-
-CMD ["packr2", "version"]
-
-
 # Notes for self:
 # Windows:
 # GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++  go build -ldflags "-extldflags '-static'" -tags extended
diff --git a/go.mod b/go.mod
index 90cba253..2c7dc54e 100644
--- a/go.mod
+++ b/go.mod
@@ -40,7 +40,6 @@ require (
 	golang.org/x/net v0.0.0-20210520170846-37e1c6afe023
 	golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c
 	golang.org/x/term v0.0.0-20210615171337-6886f2dfbf5b // indirect
-	golang.org/x/tools v0.1.0 // indirect
 	gopkg.in/sourcemap.v1 v1.0.5 // indirect
 	gopkg.in/yaml.v2 v2.4.0
 )
@@ -87,6 +86,7 @@ require (
 	go.uber.org/atomic v1.6.0 // indirect
 	golang.org/x/mod v0.4.1 // indirect
 	golang.org/x/text v0.3.6 // indirect
+	golang.org/x/tools v0.1.0 // indirect
 	golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 // indirect
 	gopkg.in/ini.v1 v1.51.0 // indirect
 	gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c // indirect
diff --git a/go.sum b/go.sum
index 32076fd6..b1757f9f 100644
--- a/go.sum
+++ b/go.sum
@@ -589,7 +589,6 @@ github.com/rs/zerolog v1.18.0 h1:CbAm3kP2Tptby1i9sYy2MGRg0uxIN9cyDb59Ys7W8z8=
 github.com/rs/zerolog v1.18.0/go.mod h1:9nvC1axdVrAHcu/s9taAVfBuIdTZLVQmKQyvrUjF5+I=
 github.com/russross/blackfriday/v2 v2.0.1 h1:lPqVAte+HuHNfhJ/0LC98ESWRz8afy9tM/0RK8m9o+Q=
 github.com/russross/blackfriday/v2 v2.0.1/go.mod h1:+Rmxgy9KzJVeS9/2gXHxylqXiyQDYRxCVz55jmeOWTM=
-github.com/russross/blackfriday/v2 v2.0.1/go.mod h1:+Rmxgy9KzJVeS9/2gXHxylqXiyQDYRxCVz55jmeOWTM=
 github.com/ryanuber/columnize v0.0.0-20160712163229-9b3edd62028f/go.mod h1:sm1tb6uqfes/u+d4ooFouqFdy9/2g9QGwK3SQygK0Ts=
 github.com/ryszard/goskiplist v0.0.0-20150312221310-2dfbae5fcf46/go.mod h1:uAQ5PCi+MFsC7HjREoAz1BU+Mq60+05gifQSsHSDG/8=
 github.com/satori/go.uuid v1.2.0/go.mod h1:dA0hQrYB0VpLJoorglMZABFdXlWrHn1NEOzdhQKdks0=
@@ -780,7 +779,6 @@ golang.org/x/net v0.0.0-20190503192946-f4e77d36d62c/go.mod h1:t9HGtf8HONx5eT2rtn
 golang.org/x/net v0.0.0-20190522155817-f3200d17e092/go.mod h1:HSz+uSET+XFnRR8LxR5pz3Of3rY3CfYBVs4xY44aLks=
 golang.org/x/net v0.0.0-20190603091049-60506f45cf65/go.mod h1:HSz+uSET+XFnRR8LxR5pz3Of3rY3CfYBVs4xY44aLks=
 golang.org/x/net v0.0.0-20190620200207-3b0461eec859/go.mod h1:z5CRVTTTmAJ677TzLLGU+0bjPO0LkuOLi4/5GtJWs/s=
-golang.org/x/net v0.0.0-20190620200207-3b0461eec859/go.mod h1:z5CRVTTTmAJ677TzLLGU+0bjPO0LkuOLi4/5GtJWs/s=
 golang.org/x/net v0.0.0-20190628185345-da137c7871d7/go.mod h1:z5CRVTTTmAJ677TzLLGU+0bjPO0LkuOLi4/5GtJWs/s=
 golang.org/x/net v0.0.0-20190724013045-ca1201d0de80/go.mod h1:z5CRVTTTmAJ677TzLLGU+0bjPO0LkuOLi4/5GtJWs/s=
 golang.org/x/net v0.0.0-20190813141303-74dc4d7220e7/go.mod h1:z5CRVTTTmAJ677TzLLGU+0bjPO0LkuOLi4/5GtJWs/s=
@@ -952,7 +950,6 @@ golang.org/x/tools v0.0.0-20191112195655-aa38f8e97acc/go.mod h1:b+2E5dAYhXwXZwtn
 golang.org/x/tools v0.0.0-20191113191852-77e3bb0ad9e7/go.mod h1:b+2E5dAYhXwXZwtnZ6UAqBI28+e2cm9otk0dWdXHAEo=
 golang.org/x/tools v0.0.0-20191115202509-3a792d9c32b2/go.mod h1:b+2E5dAYhXwXZwtnZ6UAqBI28+e2cm9otk0dWdXHAEo=
 golang.org/x/tools v0.0.0-20191119224855-298f0cb1881e/go.mod h1:b+2E5dAYhXwXZwtnZ6UAqBI28+e2cm9otk0dWdXHAEo=
-golang.org/x/tools v0.0.0-20191119224855-298f0cb1881e/go.mod h1:b+2E5dAYhXwXZwtnZ6UAqBI28+e2cm9otk0dWdXHAEo=
 golang.org/x/tools v0.0.0-20191125144606-a911d9008d1f/go.mod h1:b+2E5dAYhXwXZwtnZ6UAqBI28+e2cm9otk0dWdXHAEo=
 golang.org/x/tools v0.0.0-20191130070609-6e064ea0cf2d/go.mod h1:b+2E5dAYhXwXZwtnZ6UAqBI28+e2cm9otk0dWdXHAEo=
 golang.org/x/tools v0.0.0-20191216173652-a0e659d51361/go.mod h1:TB2adYChydJhpapKDTa4BR/hXlZSLoq2Wpct/0txZ28=
@@ -991,10 +988,7 @@ golang.org/x/tools v0.1.0/go.mod h1:xkSsbof2nBLbhDlRMhhhyNLN/zl3eTqcnHD5viDpcZ0=
 golang.org/x/xerrors v0.0.0-20190410155217-1f06c39b4373/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
 golang.org/x/xerrors v0.0.0-20190513163551-3ee3066db522/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
 golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
-golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
 golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
-golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
-golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
 golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
 golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
 golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
@@ -1125,7 +1119,6 @@ gopkg.in/yaml.v2 v2.0.0-20170812160011-eb3733d160e7/go.mod h1:JAlM8MvJe8wmxCU4Bl
 gopkg.in/yaml.v2 v2.2.1/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
 gopkg.in/yaml.v2 v2.2.2/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
 gopkg.in/yaml.v2 v2.2.4/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
-gopkg.in/yaml.v2 v2.2.4/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
 gopkg.in/yaml.v2 v2.2.7/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
 gopkg.in/yaml.v2 v2.2.8/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
 gopkg.in/yaml.v2 v2.3.0/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
diff --git a/scripts/cross-compile.sh b/scripts/cross-compile.sh
index a5db1b61..0a876c63 100755
--- a/scripts/cross-compile.sh
+++ b/scripts/cross-compile.sh
@@ -8,8 +8,7 @@ GITHASH=`git rev-parse --short HEAD`
 STASH_VERSION=`git describe --tags --exclude latest_develop`
 
 SETENV="BUILD_DATE=\"$BUILD_DATE\" GITHASH=$GITHASH STASH_VERSION=\"$STASH_VERSION\""
-SETUP="export CGO_ENABLED=1; set -e; echo '=== Running packr ==='; make packr;"
-SETUP_FAST="export CGO_ENABLED=1;"
+SETUP="export CGO_ENABLED=1;"
 WINDOWS="echo '=== Building Windows binary ==='; $SETENV make cross-compile-windows;"
 DARWIN="echo '=== Building OSX binary ==='; $SETENV make cross-compile-osx-intel;"
 DARWIN-ARM64="echo '=== Building OSX (arm64) binary ==='; $SETENV make cross-compile-osx-applesilicon;"
@@ -19,14 +18,6 @@ LINUX_ARM32v7="echo '=== Building Linux (armv7/armhf) binary ==='; $SETENV make
 LINUX_ARM32v6="echo '=== Building Linux (armv6 | Raspberry Pi 1) binary ==='; $SETENV make cross-compile-pi;"
 BUILD_COMPLETE="echo '=== Build complete ==='"
 
-# if build target ends with -fast then use prebuilt packr2. eg amd64-fast or all-fast
-FAST=`echo "$1" | cut -d - -f 2`
-if [ "$FAST" == "fast" ]
-then
-  echo "Building without Packr2"
-  SETUP=$SETUP_FAST
-fi
-
 BUILD=`echo "$1" | cut -d - -f 1`
 if [ "$BUILD" == "windows" ]
 then
```

**Comment by kermieisinthehouse** [comment]
@bnkai 

The dockerfile stuff looks fine, but we maybe should keep the docker/gitignore entries for a little while? Or maybe not, since it'll make it obvious to delete the artifacts from developers machines... ¯\_( ͡° ͜ʖ ͡°)_/¯

**Comment by bnkai** [comment]
> @bnkai
> 
> The dockerfile stuff looks fine, but we maybe should keep the docker/gitignore entries for a little while? Or maybe not, since it'll make it obvious to delete the artifacts from developers machines... ¯_( ͡° ͜ʖ ͡°)_/¯

Yeah i removed the ignore entries just for that reason. I noticed the extra files that git diff would ignore and had to do the checkout in a new folder just to be sure they were not part of the original code :P. Imo this makes it clear that the artifacts are no more part of the code, we could remove them in a later PR though if not now.

**Comment by WithoutPants** [comment]
That'll learn me for rushing out a PR before bedtime. Remaining references should now be removed. I'm going to do some testing of the docker and cross-compile stuff. Note that I've modified the compiler dockerfile, but I won't be building another image and bumping the version until its actually necessary to do so.

**Comment by kermieisinthehouse** [comment]
Line 30, `COPY ./static /stash/static/` needs to be removed from docker/build/x86_64/Dockerfile.

**Pull request merged**
