### PR TITLE
[Feature] Add blurred background to portrait aspect ratio scene thumbnails

### LINKED ISSUE #1945: [Feature] Add blurred background to portrait aspect ratio scene thumbnails
**Is your feature request related to a problem? Please describe.**
Scene and image cards that have thumbnails with portrait/vertical aspect ratio have blank space on the left and right of the thumbnail since they cannot fill the width of their card.

**Describe the solution you'd like**
Add a background image of the thumbnail zoomed in to fill the width of the scene card and blurred. This is pretty standard for a lot of vertical/portrait aspect ratio content that that is viewed landscape viewports (which the cards are)

See here for an example https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2FyCOrqUA0ws4%2Fmaxresdefault.jpg&f=1&nofb=1

Add an option in the settings to enable/disable this feature?

### PR DESCRIPTION
**Pull request by fun-git-user**
Resolves #1945

### CODE REVIEW

**Comment by fun-git-user** [comment]
Added blurred background to image/scene cards as well

**Comment by fun-git-user** [comment]
closes #1945

**Comment by WithoutPants** [comment]
I personally think this doesn't look very good, both on the cards and in the scene player. Based on discussion on Discord, that view appears to be shared. I think this should be disabled by default, with the option to enable it via custom css.

**Comment by DogmaDragon** [comment]
There is a custom Javascript that adds this functionality to those that want it <https://docs.stashapp.cc/add-ons/scripts/#blurrycardbackground>

**Comment by kermieisinthehouse** [comment]
While all contributions are absolutely appreciated, this one seems divisive and is well served by the third party add-on.

Closing this for now.

**Pull request closed without merging**
